Crypto.find_or_create_by(ticker: "BRDG", name: "BridgeProtocol")
Crypto.find_or_create_by(ticker: "GLC", name: "GoldCoin")
Crypto.find_or_create_by(ticker: "MOAC", name: "MOAC")
Crypto.find_or_create_by(ticker: "SDC", name: "SDChain")
Crypto.find_or_create_by(ticker: "TEAM", name: "TokenStars")
Crypto.find_or_create_by(ticker: "ZNT", name: "Zenswap Network Token")
Crypto.find_or_create_by(ticker: "SHVR", name: "Shivers")
Crypto.find_or_create_by(ticker: "ETGP", name: "Ethereum Gold Project")
Crypto.find_or_create_by(ticker: "LNK", name: "Link Platform")
Crypto.find_or_create_by(ticker: "SHMN", name: "StrongHands Masternode")
Crypto.find_or_create_by(ticker: "CCT", name: "Crystal Clear")
Crypto.find_or_create_by(ticker: "DATP", name: "Decentralized Asset Trading Platform")
Crypto.find_or_create_by(ticker: "FREE", name: "FREE Coin")
Crypto.find_or_create_by(ticker: "DALC", name: "Dale Coin")
Crypto.find_or_create_by(ticker: "KNT", name: "Kora")
Crypto.find_or_create_by(ticker: "WTN", name: "Waletoken")
Crypto.find_or_create_by(ticker: "BLOC", name: "Blockcloud")
Crypto.find_or_create_by(ticker: "TVNT", name: "TravelNote")
Crypto.find_or_create_by(ticker: "YLC", name: "YoloCash")
Crypto.find_or_create_by(ticker: "XUEZ", name: "Xues")
Crypto.find_or_create_by(ticker: "XSG", name: "SnowGem")
Crypto.find_or_create_by(ticker: "XCEL", name: "XcelToken")
Crypto.find_or_create_by(ticker: "XBI", name: "Bitcoin Incognito")
Crypto.find_or_create_by(ticker: "WIX", name: "Wixlar")
Crypto.find_or_create_by(ticker: "WAB", name: "WABnetwork")
Crypto.find_or_create_by(ticker: "VERI", name: "Veritaseum")
Crypto.find_or_create_by(ticker: "UNIFY", name: "Unify")
Crypto.find_or_create_by(ticker: "TRXC", name: "TRONCLASSIC")
Crypto.find_or_create_by(ticker: "TCC", name: "The ChampCoin")
Crypto.find_or_create_by(ticker: "SAFE", name: "SAFE")
Crypto.find_or_create_by(ticker: "S4F", name: "S4FE")
Crypto.find_or_create_by(ticker: "RISE", name: "Rise")
Crypto.find_or_create_by(ticker: "QCH", name: "QChi")
Crypto.find_or_create_by(ticker: "PWR", name: "PWR Coin")
Crypto.find_or_create_by(ticker: "POSS", name: "Posscoin")
Crypto.find_or_create_by(ticker: "NSD", name: "Nasdacoin")
Crypto.find_or_create_by(ticker: "NRP", name: "Neural Protocol")
Crypto.find_or_create_by(ticker: "NOTE", name: "Dnotes")
Crypto.find_or_create_by(ticker: "NIX", name: "NIX")
Crypto.find_or_create_by(ticker: "NAVY", name: "BoatPilot Token")
Crypto.find_or_create_by(ticker: "N8V", name: "NativeCoin")
Crypto.find_or_create_by(ticker: "MTC", name: "doc.com")
Crypto.find_or_create_by(ticker: "MNTP", name: "Goldmint")
Crypto.find_or_create_by(ticker: "MICRO", name: "Micromines")
Crypto.find_or_create_by(ticker: "MATIC", name: "Matic Network")
Crypto.find_or_create_by(ticker: "KNDC", name: "KanadeCoin")
Crypto.find_or_create_by(ticker: "KLKS", name: "Kalkulus")
Crypto.find_or_create_by(ticker: "JOINT", name: "Joint Ventures")
Crypto.find_or_create_by(ticker: "JET", name: "Jetcoin")
Crypto.find_or_create_by(ticker: "IETH", name: "iEthereum")
Crypto.find_or_create_by(ticker: "IBTC", name: "iBTC")
Crypto.find_or_create_by(ticker: "HERB", name: "Herbalist Token")
Crypto.find_or_create_by(ticker: "HELP", name: "GoHelpFund")
Crypto.find_or_create_by(ticker: "FTN", name: "Fountain")
Crypto.find_or_create_by(ticker: "FOXT", name: "Fox Trading")
Crypto.find_or_create_by(ticker: "EXO", name: "Exosis")
Crypto.find_or_create_by(ticker: "EVN", name: "Envion")
Crypto.find_or_create_by(ticker: "EVC", name: "EventChain")
Crypto.find_or_create_by(ticker: "ETHO", name: "Ether-1")
Crypto.find_or_create_by(ticker: "ERC20", name: "ERC20")
Crypto.find_or_create_by(ticker: "ELTCOIN", name: "ELTCOIN")
Crypto.find_or_create_by(ticker: "ELD", name: "electrumdark")
Crypto.find_or_create_by(ticker: "DTX", name: "Digital Ticks")
Crypto.find_or_create_by(ticker: "DSR", name: "Desire")
Crypto.find_or_create_by(ticker: "DIME", name: "Dimecoin")
Crypto.find_or_create_by(ticker: "DCTO", name: "Decentralized Crypto Token Markets")
Crypto.find_or_create_by(ticker: "CYL", name: "Crystal Token")
Crypto.find_or_create_by(ticker: "CSOUL", name: "CryptoSoul")
Crypto.find_or_create_by(ticker: "CL", name: "Coinlancer")
Crypto.find_or_create_by(ticker: "CCO", name: "Ccore Token")
Crypto.find_or_create_by(ticker: "BTW", name: "BitWhite")
Crypto.find_or_create_by(ticker: "BTR", name: "Bitether")
Crypto.find_or_create_by(ticker: "BTK", name: "Bitcoin Token")
Crypto.find_or_create_by(ticker: "BOUTS", name: "BoutsPro")
Crypto.find_or_create_by(ticker: "BON", name: "Bonpay")
Crypto.find_or_create_by(ticker: "BNANA", name: "Chimpion")
Crypto.find_or_create_by(ticker: "BIS", name: "Bismuth")
Crypto.find_or_create_by(ticker: "CTRT", name: "Cryptrust")
Crypto.find_or_create_by(ticker: "BELA", name: "Bela")
Crypto.find_or_create_by(ticker: "BEET", name: "Beetle Coin")
Crypto.find_or_create_by(ticker: "BBT", name: "BitBoost")
Crypto.find_or_create_by(ticker: "B2B", name: "B2BX")
Crypto.find_or_create_by(ticker: "AUX", name: "Auxilium")
Crypto.find_or_create_by(ticker: "ARO", name: "Arionum")
Crypto.find_or_create_by(ticker: "ARAW", name: "ARAW Token")
Crypto.find_or_create_by(ticker: "APC", name: "Alpha Coin")
Crypto.find_or_create_by(ticker: "AAA", name: "Abulaba")
Crypto.find_or_create_by(ticker: "WELL", name: "WELL")
Crypto.find_or_create_by(ticker: "KAT", name: "Kambria")
Crypto.find_or_create_by(ticker: "XDAG", name: "Dagger")
Crypto.find_or_create_by(ticker: "BUD", name: "Buddy")
Crypto.find_or_create_by(ticker: "TRF", name: "Travelflex")
Crypto.find_or_create_by(ticker: "TPAY", name: "TokenPay")
Crypto.find_or_create_by(ticker: "PLAY", name: "HeroCoin")
Crypto.find_or_create_by(ticker: "PKC", name: "Pikcio Chain")
Crypto.find_or_create_by(ticker: "MIB", name: "MIB")
Crypto.find_or_create_by(ticker: "BDS", name: "Borderless")
Crypto.find_or_create_by(ticker: "BITE", name: "BitEthereum")
Crypto.find_or_create_by(ticker: "KUE", name: "Kuende")
Crypto.find_or_create_by(ticker: "BST", name: "Blocksquare Token")
Crypto.find_or_create_by(ticker: "CREDO", name: "Credo")
Crypto.find_or_create_by(ticker: "KST", name: "StarKST")
Crypto.find_or_create_by(ticker: "18C", name: "Block18")
Crypto.find_or_create_by(ticker: "ACDC", name: "VOLT")
Crypto.find_or_create_by(ticker: "ATOM", name: "Cosmos")
Crypto.find_or_create_by(ticker: "BCW", name: "Bitcoin Wonder")
Crypto.find_or_create_by(ticker: "BEC", name: "Beauty")
Crypto.find_or_create_by(ticker: "BKBT", name: "BeeKan")
Crypto.find_or_create_by(ticker: "BRC", name: "BaerChain")
Crypto.find_or_create_by(ticker: "BTH", name: "Bitcoin Hot")
Crypto.find_or_create_by(ticker: "BTP", name: "Bitpound")
Crypto.find_or_create_by(ticker: "BTSU", name: "Bitsou")
Crypto.find_or_create_by(ticker: "BUT", name: "BitUP Token")
Crypto.find_or_create_by(ticker: "BVT", name: "VTChain")
Crypto.find_or_create_by(ticker: "CAI", name: "CAI Token")
Crypto.find_or_create_by(ticker: "CCCM", name: "Coindom")
Crypto.find_or_create_by(ticker: "CDC", name: "Commerce Data Connection")
Crypto.find_or_create_by(ticker: "CENT", name: "Center Coin")
Crypto.find_or_create_by(ticker: "CIC", name: "CIChain")
Crypto.find_or_create_by(ticker: "CODY", name: "Coindy")
Crypto.find_or_create_by(ticker: "CONTENT", name: "Content Protocol Token")
Crypto.find_or_create_by(ticker: "CPCN", name: "Capricoin")
Crypto.find_or_create_by(ticker: "CRN", name: "ChronoCoin")
Crypto.find_or_create_by(ticker: "DASC", name: "DasCoin")
Crypto.find_or_create_by(ticker: "DDM", name: "DDMCoin")
Crypto.find_or_create_by(ticker: "DIP", name: "Etherisc")
Crypto.find_or_create_by(ticker: "DUC", name: "DucatusCoin")
Crypto.find_or_create_by(ticker: "DVC", name: "DragonVein Coin")
Crypto.find_or_create_by(ticker: "EDU", name: "EduCoin")
Crypto.find_or_create_by(ticker: "EGCC", name: "Engine")
Crypto.find_or_create_by(ticker: "ENTCASH", name: "ENTCash")
Crypto.find_or_create_by(ticker: "EPC", name: "Electronic PK Chain")
Crypto.find_or_create_by(ticker: "FAB", name: "Fast Access Blockchain")
Crypto.find_or_create_by(ticker: "FACC", name: "FACC")
Crypto.find_or_create_by(ticker: "FAIRGAME", name: "FAIRGAME")
Crypto.find_or_create_by(ticker: "FCC", name: "Five Colors Coin")
Crypto.find_or_create_by(ticker: "GLDR", name: "Golder")
Crypto.find_or_create_by(ticker: "GMTK", name: "Game Token")
Crypto.find_or_create_by(ticker: "GON", name: "GoNetwork")
Crypto.find_or_create_by(ticker: "GRAM", name: "GRAM Coin")
Crypto.find_or_create_by(ticker: "GVE", name: "Globalvillage Ecosystem")
Crypto.find_or_create_by(ticker: "HAPPY", name: "Happy Token")
Crypto.find_or_create_by(ticker: "HDAC", name: "Hdac")
Crypto.find_or_create_by(ticker: "HOTC", name: "HOTchain")
Crypto.find_or_create_by(ticker: "HPT", name: "Huobi Pool Token")
Crypto.find_or_create_by(ticker: "HPY", name: "Hyper Pay")
Crypto.find_or_create_by(ticker: "HUSD", name: "HUSD")
Crypto.find_or_create_by(ticker: "IDT", name: "InvestDigital")
Crypto.find_or_create_by(ticker: "IIC", name: "Intelligent Investment Chain")
Crypto.find_or_create_by(ticker: "IRIS", name: "IRISnet")
Crypto.find_or_create_by(ticker: "KRWB", name: "KRWb")
Crypto.find_or_create_by(ticker: "KUKY", name: "Kuky Star")
Crypto.find_or_create_by(ticker: "LFC", name: "Linfinity")
Crypto.find_or_create_by(ticker: "LIGHT", name: "LightChain")
Crypto.find_or_create_by(ticker: "LIT", name: "Lition")
Crypto.find_or_create_by(ticker: "LVTC", name: "LVTC")
Crypto.find_or_create_by(ticker: "MEET", name: "CoinMeet")
Crypto.find_or_create_by(ticker: "MEX", name: "MEX")
Crypto.find_or_create_by(ticker: "MINX", name: "InnovaMinex")
Crypto.find_or_create_by(ticker: "MOF", name: "Molecular Future")
Crypto.find_or_create_by(ticker: "MRIT", name: "Merit")
Crypto.find_or_create_by(ticker: "MT", name: "MyToken")
Crypto.find_or_create_by(ticker: "MUSK", name: "Musk")
Crypto.find_or_create_by(ticker: "MVPT", name: "MediaLink")
Crypto.find_or_create_by(ticker: "NBOT", name: "NakaBOT")
Crypto.find_or_create_by(ticker: "NEW", name: "Newton")
Crypto.find_or_create_by(ticker: "NNB", name: "NNB token")
Crypto.find_or_create_by(ticker: "OF", name: "OFCOIN")
Crypto.find_or_create_by(ticker: "OKB", name: "OKEx Utility Token")
Crypto.find_or_create_by(ticker: "ONTGAS", name: "Ontology Gas")
Crypto.find_or_create_by(ticker: "OZX", name: "OZEX")
Crypto.find_or_create_by(ticker: "PC", name: "PromotionChain")
Crypto.find_or_create_by(ticker: "PORTAL", name: "Portal")
Crypto.find_or_create_by(ticker: "QC", name: "QC")
Crypto.find_or_create_by(ticker: "RBG", name: "RankingBall")
Crypto.find_or_create_by(ticker: "RBTC", name: "RSK")
Crypto.find_or_create_by(ticker: "RCCC", name: "RCCC")
Crypto.find_or_create_by(ticker: "RCOIN", name: "Rcoin")
Crypto.find_or_create_by(ticker: "SBA", name: "simplyBrand")
Crypto.find_or_create_by(ticker: "SHE", name: "ShineChain")
Crypto.find_or_create_by(ticker: "SKYM", name: "Skymap")
Crypto.find_or_create_by(ticker: "SLT", name: "Social Lending Token")
Crypto.find_or_create_by(ticker: "SMARTUP", name: "SmartUp")
Crypto.find_or_create_by(ticker: "STB", name: "STB")
Crypto.find_or_create_by(ticker: "STC", name: "StarChain")
Crypto.find_or_create_by(ticker: "SWET", name: "SWE Token")
Crypto.find_or_create_by(ticker: "THM", name: "Themis Chain")
Crypto.find_or_create_by(ticker: "THPC", name: "Texas Hold'em Poker Chain")
Crypto.find_or_create_by(ticker: "TMTG", name: "The Midas Touch Gold")
Crypto.find_or_create_by(ticker: "TOC", name: "Tobigca")
Crypto.find_or_create_by(ticker: "TOPC", name: "TopChain")
Crypto.find_or_create_by(ticker: "TOS", name: "ThingsOperatingSystem")
Crypto.find_or_create_by(ticker: "TRA", name: "project:Trave")
Crypto.find_or_create_by(ticker: "TVND", name: "TrueVND")
Crypto.find_or_create_by(ticker: "TVS", name: "TrustVerse")
Crypto.find_or_create_by(ticker: "UBTC", name: "United Bitcoin")
Crypto.find_or_create_by(ticker: "UC", name: "YouLive Coin")
Crypto.find_or_create_by(ticker: "UCT", name: "Ubique Chain of Things")
Crypto.find_or_create_by(ticker: "UIP", name: "UnlimitedIP")
Crypto.find_or_create_by(ticker: "VBK", name: "VeriBlock")
Crypto.find_or_create_by(ticker: "VEEN", name: "VEEN")
Crypto.find_or_create_by(ticker: "VIAT", name: "ViaBTC Token")
Crypto.find_or_create_by(ticker: "VOLLAR", name: "VOLLAR")
Crypto.find_or_create_by(ticker: "VSC", name: "vSport Coin")
Crypto.find_or_create_by(ticker: "VTHO", name: "VeThor Token")
Crypto.find_or_create_by(ticker: "WBL", name: "WIZBL")
Crypto.find_or_create_by(ticker: "WBTC", name: "Wrapped Bitcoin")
Crypto.find_or_create_by(ticker: "WHEN", name: "WHEN Token")
Crypto.find_or_create_by(ticker: "WIN", name: "WinToken")
Crypto.find_or_create_by(ticker: "XBG", name: "Bitgrin")
Crypto.find_or_create_by(ticker: "XT", name: "X Token")
Crypto.find_or_create_by(ticker: "YOU", name: "YOU COIN")
Crypto.find_or_create_by(ticker: "ZAT", name: "ZATGO")
Crypto.find_or_create_by(ticker: "ZB", name: "ZB")
Crypto.find_or_create_by(ticker: "ZJLT", name: "ZJLT Distributed Factoring Network")
Crypto.find_or_create_by(ticker: "ZLA", name: "Zilla")
Crypto.find_or_create_by(ticker: "AAC", name: "Acute Angle Cloud")
Crypto.find_or_create_by(ticker: "ABBC", name: "ABBC Coin")
Crypto.find_or_create_by(ticker: "ACE", name: "TokenStars")
Crypto.find_or_create_by(ticker: "AERGO", name: "Aergo")
Crypto.find_or_create_by(ticker: "AIDOC", name: "AI Doctor")
Crypto.find_or_create_by(ticker: "ALI", name: "AiLink Token")
Crypto.find_or_create_by(ticker: "ALX", name: "ALX Token")
Crypto.find_or_create_by(ticker: "ANKR", name: "Ankr")
Crypto.find_or_create_by(ticker: "APL", name: "Apollo Coin")
Crypto.find_or_create_by(ticker: "ATX", name: "Aston")
Crypto.find_or_create_by(ticker: "BCV", name: "BitCapitalVendor")
Crypto.find_or_create_by(ticker: "BEAM", name: "BEAM")
Crypto.find_or_create_by(ticker: "BETHER", name: "Bethereum")
Crypto.find_or_create_by(ticker: "BITTORRENT", name: "BitTorrent")
Crypto.find_or_create_by(ticker: "BIX", name: "Bibox Token")
Crypto.find_or_create_by(ticker: "BLN", name: "BlackNet")
Crypto.find_or_create_by(ticker: "BSTN", name: "BitStation")
Crypto.find_or_create_by(ticker: "BTB", name: "Bitibu Coin")
Crypto.find_or_create_by(ticker: "BTN", name: "BitNewChain")
Crypto.find_or_create_by(ticker: "BTNT", name: "BitNautic Token")
Crypto.find_or_create_by(ticker: "BTU", name: "BTU Protocol")
Crypto.find_or_create_by(ticker: "CELR", name: "Celer Network")
Crypto.find_or_create_by(ticker: "COVA", name: "COVA")
Crypto.find_or_create_by(ticker: "CRO", name: "Crypto Chain Token")
Crypto.find_or_create_by(ticker: "CVNT", name: "Content Value Network")
Crypto.find_or_create_by(ticker: "DAC", name: "Davinci Coin")
Crypto.find_or_create_by(ticker: "ECA", name: "Electra")
Crypto.find_or_create_by(ticker: "EDC", name: "E-Dinar Coin")
Crypto.find_or_create_by(ticker: "EKT", name: "EKT")
Crypto.find_or_create_by(ticker: "ELA", name: "Elastos")
Crypto.find_or_create_by(ticker: "ELIX", name: "elixir")
Crypto.find_or_create_by(ticker: "ENRG", name: "Energycoin")
Crypto.find_or_create_by(ticker: "EQUAD", name: "Quadrant Protocol")
Crypto.find_or_create_by(ticker: "FET", name: "Fetch")
Crypto.find_or_create_by(ticker: "ZIP", name: "Zipper")
Crypto.find_or_create_by(ticker: "YEE", name: "YEE")
Crypto.find_or_create_by(ticker: "XMCT", name: "XMED Chain")
Crypto.find_or_create_by(ticker: "XAS", name: "Asch")
Crypto.find_or_create_by(ticker: "WWB", name: "Wowbit")
Crypto.find_or_create_by(ticker: "FNKOS", name: "Foglink")
Crypto.find_or_create_by(ticker: "GETX", name: "InsChain")
Crypto.find_or_create_by(ticker: "GSC", name: "Global Social Chain")
Crypto.find_or_create_by(ticker: "GXC", name: "GXChain")
Crypto.find_or_create_by(ticker: "HB", name: "HeartBout")
Crypto.find_or_create_by(ticker: "HLC", name: "HalalChain")
Crypto.find_or_create_by(ticker: "HMC", name: "Hi Mutual Society")
Crypto.find_or_create_by(ticker: "HPB", name: "High Performance Blockchain")
Crypto.find_or_create_by(ticker: "HT", name: "Huobi Token")
Crypto.find_or_create_by(ticker: "HYC", name: "HYCON")
Crypto.find_or_create_by(ticker: "IMP", name: "Ether Kingdoms Token")
Crypto.find_or_create_by(ticker: "ISR", name: "Insureum")
Crypto.find_or_create_by(ticker: "KAN", name: "BitKan")
Crypto.find_or_create_by(ticker: "KCASH", name: "Kcash")
Crypto.find_or_create_by(ticker: "LAMB", name: "Lambda")
Crypto.find_or_create_by(ticker: "LATX", name: "LatiumX")
Crypto.find_or_create_by(ticker: "LBTC", name: "Lightning Bitcoin")
Crypto.find_or_create_by(ticker: "LET", name: "LinkEye")
Crypto.find_or_create_by(ticker: "LUX", name: "LUXCoin")
Crypto.find_or_create_by(ticker: "LXT", name: "Litex")
Crypto.find_or_create_by(ticker: "META", name: "Metadium")
Crypto.find_or_create_by(ticker: "NOBS", name: "No BS Crypto")
Crypto.find_or_create_by(ticker: "NTY", name: "WoNextywbit")
Crypto.find_or_create_by(ticker: "OPEN", name: "OpenPlatform")
Crypto.find_or_create_by(ticker: "ORBS", name: "Orbs")
Crypto.find_or_create_by(ticker: "OVC", name: " OVCODE")
Crypto.find_or_create_by(ticker: "PCH", name: "POPCHAIN")
Crypto.find_or_create_by(ticker: "PI", name: "PHCHAIN")
Crypto.find_or_create_by(ticker: "PLA", name: "PlayChip")
Crypto.find_or_create_by(ticker: "PRA", name: "ProChain")
Crypto.find_or_create_by(ticker: "PSM", name: "PRASM")
Crypto.find_or_create_by(ticker: "QUN", name: "QunQun")
Crypto.find_or_create_by(ticker: "RCT", name: "RealChain")
Crypto.find_or_create_by(ticker: "RNT", name: "OneRoot")
Crypto.find_or_create_by(ticker: "SCCN", name: "Stem Cell Coin")
Crypto.find_or_create_by(ticker: "SDA", name: "SDChain")
Crypto.find_or_create_by(ticker: "SERV", name: "Serve")
Crypto.find_or_create_by(ticker: "SIM", name: "Simmitri")
Crypto.find_or_create_by(ticker: "SKB", name: "Sakura Bloom")
Crypto.find_or_create_by(ticker: "SRCOIN", name: "SRCOIN")
Crypto.find_or_create_by(ticker: "SSC", name: "SelfSell")
Crypto.find_or_create_by(ticker: "SSP", name: "Smartshare")
Crypto.find_or_create_by(ticker: "TEN", name: "TOKENOMY")
Crypto.find_or_create_by(ticker: "TFUEL", name: "ThetaFuel")
Crypto.find_or_create_by(ticker: "TOP", name: "Top Network")
Crypto.find_or_create_by(ticker: "TRIO", name: "Tripio")
Crypto.find_or_create_by(ticker: "TSL", name: "Energo")
Crypto.find_or_create_by(ticker: "UGAS", name: "Ultrain")
Crypto.find_or_create_by(ticker: "UDOO", name: "Howdoo")
Crypto.find_or_create_by(ticker: "UGC", name: "ugChain")
Crypto.find_or_create_by(ticker: "UTNP", name: "Universa Token")
Crypto.find_or_create_by(ticker: "ULT", name: "Ultiledger")
Crypto.find_or_create_by(ticker: "VEIL", name: "Veil")
Crypto.find_or_create_by(ticker: "VRA", name: "VERAsity")
Crypto.find_or_create_by(ticker: "VSF", name: "VeriSafe")
Crypto.find_or_create_by(ticker: "WICC", name: "WaykiChain")
Crypto.find_or_create_by(ticker: "WLK", name: "Wolk")
Crypto.find_or_create_by(ticker: "FTEC", name: "FTEC")
Crypto.find_or_create_by(ticker: "SKYFT", name: "SKYFchain")
Crypto.find_or_create_by(ticker: "CCC", name: "Crush Crypto Core")
Crypto.find_or_create_by(ticker: "SKRP", name: "Skraps")
Crypto.find_or_create_by(ticker: "WZI", name: "Wizzle Infinity Token")
Crypto.find_or_create_by(ticker: "SHPING", name: "SHPING")
Crypto.find_or_create_by(ticker: "CSX", name: "Casax")
Crypto.find_or_create_by(ticker: "VTY", name: "VERITY")
Crypto.find_or_create_by(ticker: "XENC", name: "xenchain")
Crypto.find_or_create_by(ticker: "AKYU", name: "Akyumen")
Crypto.find_or_create_by(ticker: "EET", name: "Energy Eco Token")
Crypto.find_or_create_by(ticker: "KIT", name: "KitToken")
Crypto.find_or_create_by(ticker: "MOVI", name: "MoviToken")
Crypto.find_or_create_by(ticker: "NCA", name: "Neironix")
Crypto.find_or_create_by(ticker: "PAR", name: "Parachute")
Crypto.find_or_create_by(ticker: "PETH", name: "Pooled Ether Token")
Crypto.find_or_create_by(ticker: "VIO", name: "Vio")
Crypto.find_or_create_by(ticker: "VSYS", name: "V Systems")
Crypto.find_or_create_by(ticker: "DSCP", name: "Disciplina")
Crypto.find_or_create_by(ticker: "EQL", name: "EQUAL")
Crypto.find_or_create_by(ticker: "RIF", name: "RSK Infrastructure Framework")
Crypto.find_or_create_by(ticker: "LCD", name: "Lucyd")
Crypto.find_or_create_by(ticker: "PRFT", name: "Proof")
Crypto.find_or_create_by(ticker: "UMT", name: "Universal Mobile Token")
Crypto.find_or_create_by(ticker: "NTK2", name: "Netkoin")
Crypto.find_or_create_by(ticker: "MESH", name: "MeshBox")
Crypto.find_or_create_by(ticker: "GMR", name: "GIMMER")
Crypto.find_or_create_by(ticker: "CUZ", name: "Cool Cousin")
Crypto.find_or_create_by(ticker: "BITCAR", name: "BitCar")
Crypto.find_or_create_by(ticker: "BCST", name: "Blockchain Store")
Crypto.find_or_create_by(ticker: "ACAD", name: "Academy")
Crypto.find_or_create_by(ticker: "ABTC", name: "AML BitCoin")
Crypto.find_or_create_by(ticker: "ABA", name: "EcoBall")
Crypto.find_or_create_by(ticker: "0XBTC", name: "0xBitcoin")
Crypto.find_or_create_by(ticker: "SAT2", name: "Social Activity Token")
Crypto.find_or_create_by(ticker: "ACO", name: "A!Coin")
Crypto.find_or_create_by(ticker: "BTF", name: "BTF")
Crypto.find_or_create_by(ticker: "EMTV", name: "Multiversum")
Crypto.find_or_create_by(ticker: "FRES", name: "FRESCO")
Crypto.find_or_create_by(ticker: "UTN", name: "Universa")
Crypto.find_or_create_by(ticker: "ARCONA", name: "ARCONA")
Crypto.find_or_create_by(ticker: "BRN", name: "Brainmab")
Crypto.find_or_create_by(ticker: "BTM", name: "Bytom")
Crypto.find_or_create_by(ticker: "BUS", name: "BTU support")
Crypto.find_or_create_by(ticker: "CAT2", name: "BitClave")
Crypto.find_or_create_by(ticker: "CDCC", name: "CDCC")
Crypto.find_or_create_by(ticker: "DAD", name: "Decentralized Digital Advertising")
Crypto.find_or_create_by(ticker: "EBKC", name: "Ekkoblock")
Crypto.find_or_create_by(ticker: "EEE", name: "Elementh token")
Crypto.find_or_create_by(ticker: "EQC", name: "Qchain")
Crypto.find_or_create_by(ticker: "EXRT", name: "EXRT")
Crypto.find_or_create_by(ticker: "GUTS", name: "GUTS")
Crypto.find_or_create_by(ticker: "H2O", name: "Hydrominer")
Crypto.find_or_create_by(ticker: "INNBC", name: "InnovativeBioResearch")
Crypto.find_or_create_by(ticker: "JBC", name: "Japan Brand Coin")
Crypto.find_or_create_by(ticker: "KYT", name: "Keyrpto Token")
Crypto.find_or_create_by(ticker: "LCK", name: "LuckCash")
Crypto.find_or_create_by(ticker: "MRS", name: "Marginless")
Crypto.find_or_create_by(ticker: "MUXE", name: "MUXE")
Crypto.find_or_create_by(ticker: "NPCL", name: "NPCL")
Crypto.find_or_create_by(ticker: "OAK", name: "Acorn Collective Token")
Crypto.find_or_create_by(ticker: "PITCH", name: "PitchPITCH")
Crypto.find_or_create_by(ticker: "RIK", name: "Rik coin")
Crypto.find_or_create_by(ticker: "RRT", name: "Red Pulse")
Crypto.find_or_create_by(ticker: "SILK", name: "SilkChain")
Crypto.find_or_create_by(ticker: "SLX", name: "Slate")
Crypto.find_or_create_by(ticker: "SOLVE", name: "Solve.Care")
Crypto.find_or_create_by(ticker: "SUNC", name: "SunChain")
Crypto.find_or_create_by(ticker: "T2T", name: "Traceto")
Crypto.find_or_create_by(ticker: "TDH", name: "TrustedHealth")
Crypto.find_or_create_by(ticker: "TIV", name: "TI-Value")
Crypto.find_or_create_by(ticker: "TRAD", name: "Tradcoin")
Crypto.find_or_create_by(ticker: "UBBEY", name: "UBBEY")
Crypto.find_or_create_by(ticker: "VXV", name: "Vectorspace AI")
Crypto.find_or_create_by(ticker: "WBT", name: "Whalesburg Token")
Crypto.find_or_create_by(ticker: "WLO", name: "Wollo")
Crypto.find_or_create_by(ticker: "FTXT", name: "ClearPoll")
Crypto.find_or_create_by(ticker: "CET", name: "Dicet")
Crypto.find_or_create_by(ticker: "POA20", name: "POA20")
Crypto.find_or_create_by(ticker: "TILE", name: "Loomia Tile")
Crypto.find_or_create_by(ticker: "PBTT", name: "Purple Butterfly Trading")
Crypto.find_or_create_by(ticker: "ADI", name: "Aditus")
Crypto.find_or_create_by(ticker: "OX", name: "OX Fina")
Crypto.find_or_create_by(ticker: "SND", name: "SandCoin")
Crypto.find_or_create_by(ticker: "PRIX", name: "Privatix")
Crypto.find_or_create_by(ticker: "RTB", name: "AB-CHAIN")
Crypto.find_or_create_by(ticker: "SKR", name: "Skrilla")
Crypto.find_or_create_by(ticker: "POLL", name: "FUTURAX")
Crypto.find_or_create_by(ticker: "J8T", name: "JET8 Token")
Crypto.find_or_create_by(ticker: "WTT", name: "Giga Watt Token")
Crypto.find_or_create_by(ticker: "HIT", name: "Hitchain")
Crypto.find_or_create_by(ticker: "CNN", name: "Content Neutrality Network")
Crypto.find_or_create_by(ticker: "ESS", name: "Essentia.One")
Crypto.find_or_create_by(ticker: "YEED", name: "YGGDRASH")
Crypto.find_or_create_by(ticker: "EXRN", name: "EXRNchain")
Crypto.find_or_create_by(ticker: "BNC", name: "Bionic")
Crypto.find_or_create_by(ticker: "KIN", name: "Kin")
Crypto.find_or_create_by(ticker: "HAND", name: "ShowHand")
Crypto.find_or_create_by(ticker: "XRT", name: "XRT")
Crypto.find_or_create_by(ticker: "TIPS", name: "FedoraCoin")
Crypto.find_or_create_by(ticker: "TOTO", name: "TouristToken")
Crypto.find_or_create_by(ticker: "USDT", name: "Tether")
Crypto.find_or_create_by(ticker: "BEZ", name: "Bezop")
Crypto.find_or_create_by(ticker: "ATM", name: "ATMChain")
Crypto.find_or_create_by(ticker: "DTRC", name: "Datarius Credit")
Crypto.find_or_create_by(ticker: "HST", name: "Decision Token")
Crypto.find_or_create_by(ticker: "RTE", name: "Rate3")
Crypto.find_or_create_by(ticker: "YUP", name: "Crowdholding")
Crypto.find_or_create_by(ticker: "MFG", name: "SyncFab")
Crypto.find_or_create_by(ticker: "INV", name: "Invacio Coin")
Crypto.find_or_create_by(ticker: "IFT", name: "InvestFeed")
Crypto.find_or_create_by(ticker: "RATING", name: "Rating")
Crypto.find_or_create_by(ticker: "DACC", name: "DACC")
Crypto.find_or_create_by(ticker: "DBIX", name: "DubaiCoin")
Crypto.find_or_create_by(ticker: "XBP", name: "BlitzPredict")
Crypto.find_or_create_by(ticker: "ABL", name: "Airbloc")
Crypto.find_or_create_by(ticker: "USDS", name: "StableUSD")
Crypto.find_or_create_by(ticker: "PIVX", name: "PIVX")
Crypto.find_or_create_by(ticker: "FTC", name: "Feathercoin")
Crypto.find_or_create_by(ticker: "EOSDAC", name: "eosDAC")
Crypto.find_or_create_by(ticker: "BITB", name: "Bean Cash")
Crypto.find_or_create_by(ticker: "PPT", name: "Populous")
Crypto.find_or_create_by(ticker: "UUU", name: "U Network")
Crypto.find_or_create_by(ticker: "MRK", name: "Mark Space")
Crypto.find_or_create_by(ticker: "SWM", name: "Swarm Fund Token")
Crypto.find_or_create_by(ticker: "XMX", name: "XMAX")
Crypto.find_or_create_by(ticker: "XRP", name: "Ripple")
Crypto.find_or_create_by(ticker: "CEDEX", name: "CEDEX Token")
Crypto.find_or_create_by(ticker: "INS", name: "INS Ecosystem")
Crypto.find_or_create_by(ticker: "UBEX", name: "UBEX")
Crypto.find_or_create_by(ticker: "QWARK", name: "Qwark")
Crypto.find_or_create_by(ticker: "BRX", name: "Breakout Stake")
Crypto.find_or_create_by(ticker: "VIA", name: "Viacoin")
Crypto.find_or_create_by(ticker: "DATA", name: "Streamr DATAcoin")
Crypto.find_or_create_by(ticker: "PLU", name: "Pluton")
Crypto.find_or_create_by(ticker: "SALT", name: "SALT")
Crypto.find_or_create_by(ticker: "PLR", name: "Pillar")
Crypto.find_or_create_by(ticker: "ELE", name: "Elementrem")
Crypto.find_or_create_by(ticker: "LGO", name: "Legolas")
Crypto.find_or_create_by(ticker: "DIT", name: "Direct Insurance Token")
Crypto.find_or_create_by(ticker: "RUFF", name: "RuffChain")
Crypto.find_or_create_by(ticker: "ETBS", name: "Ethbits")
Crypto.find_or_create_by(ticker: "CPT", name: "Cryptaur")
Crypto.find_or_create_by(ticker: "LND", name: "Lendingblock")
Crypto.find_or_create_by(ticker: "KMD", name: "Komodo")
Crypto.find_or_create_by(ticker: "PAI", name: "Project PAI")
Crypto.find_or_create_by(ticker: "PAX", name: "Paxos Standard")
Crypto.find_or_create_by(ticker: "STEEM", name: "Steem")
Crypto.find_or_create_by(ticker: "CHX", name: "Own")
Crypto.find_or_create_by(ticker: "ART", name: "Maecenas")
Crypto.find_or_create_by(ticker: "ZRX", name: "0x")
Crypto.find_or_create_by(ticker: "USC", name: "Coinfix")
Crypto.find_or_create_by(ticker: "QLC", name: "QLINK")
Crypto.find_or_create_by(ticker: "SKY", name: "Skycoin")
Crypto.find_or_create_by(ticker: "MAS", name: "Midas Protocol")
Crypto.find_or_create_by(ticker: "AID", name: "AidCoin")
Crypto.find_or_create_by(ticker: "SHIP", name: "ShipChain")
Crypto.find_or_create_by(ticker: "BNB", name: "Binance Coin")
Crypto.find_or_create_by(ticker: "INK", name: "Ink")
Crypto.find_or_create_by(ticker: "IOT", name: "IOTA")
Crypto.find_or_create_by(ticker: "DEC", name: "Darico Ecosystem Coin")
Crypto.find_or_create_by(ticker: "OWN", name: "OwnData")
Crypto.find_or_create_by(ticker: "MXC", name: "Machine Xchange Coin")
Crypto.find_or_create_by(ticker: "MOBI", name: "Mobius")
Crypto.find_or_create_by(ticker: "XZC", name: "ZCoin")
Crypto.find_or_create_by(ticker: "SNR", name: "Sonder")
Crypto.find_or_create_by(ticker: "SYNX", name: "Syndicate")
Crypto.find_or_create_by(ticker: "MVP", name: "Merculet")
Crypto.find_or_create_by(ticker: "ATL", name: "ATLANT")
Crypto.find_or_create_by(ticker: "IHT", name: "IHT Real Estate Protocol")
Crypto.find_or_create_by(ticker: "MEDX", name: "MediBlocX")
Crypto.find_or_create_by(ticker: "FACE", name: "Faceter")
Crypto.find_or_create_by(ticker: "LIF", name: "Lif")
Crypto.find_or_create_by(ticker: "GET", name: "Themis GET")
Crypto.find_or_create_by(ticker: "FDZ", name: "Friendz")
Crypto.find_or_create_by(ticker: "CVT", name: "CyberVein")
Crypto.find_or_create_by(ticker: "AE", name: "Aeternity")
Crypto.find_or_create_by(ticker: "INT", name: "Internet Node Token")
Crypto.find_or_create_by(ticker: "BSV", name: "Bitcoin SV")
Crypto.find_or_create_by(ticker: "NXT", name: "Nxt")
Crypto.find_or_create_by(ticker: "UP", name: "UpToken")
Crypto.find_or_create_by(ticker: "SNC", name: "SunContract")
Crypto.find_or_create_by(ticker: "AEON", name: "Aeon")
Crypto.find_or_create_by(ticker: "QBT", name: "Qbao")
Crypto.find_or_create_by(ticker: "PST", name: "Primas")
Crypto.find_or_create_by(ticker: "DMD", name: "Diamond")
Crypto.find_or_create_by(ticker: "BTC", name: "Bitcoin")
Crypto.find_or_create_by(ticker: "BITS", name: "Bitswift")
Crypto.find_or_create_by(ticker: "IOST", name: "IOStoken")
Crypto.find_or_create_by(ticker: "C20", name: "CRYPTO20")
Crypto.find_or_create_by(ticker: "SPN", name: "Sapien Network")
Crypto.find_or_create_by(ticker: "SNT", name: "Status")
Crypto.find_or_create_by(ticker: "BSD", name: "BitSend")
Crypto.find_or_create_by(ticker: "RFR", name: "Refereum")
Crypto.find_or_create_by(ticker: "ENGT", name: "Engagement Token")
Crypto.find_or_create_by(ticker: "MED", name: "MediBloc")
Crypto.find_or_create_by(ticker: "TV", name: "Tokenville")
Crypto.find_or_create_by(ticker: "XHV", name: "Haven Protocol")
Crypto.find_or_create_by(ticker: "GNO", name: "Gnosis")
Crypto.find_or_create_by(ticker: "GENE", name: "GeneSourceCodeChain")
Crypto.find_or_create_by(ticker: "SMART", name: "SmartBillions")
Crypto.find_or_create_by(ticker: "WTC", name: "Walton")
Crypto.find_or_create_by(ticker: "SEER", name: "SEER")
Crypto.find_or_create_by(ticker: "ZSC", name: "Zeusshield")
Crypto.find_or_create_by(ticker: "NMR", name: "Numeraire")
Crypto.find_or_create_by(ticker: "MTX", name: "Matryx")
Crypto.find_or_create_by(ticker: "PASS", name: "Blockpass")
Crypto.find_or_create_by(ticker: "CMT", name: "CyberMiles")
Crypto.find_or_create_by(ticker: "DPY", name: "Delphy")
Crypto.find_or_create_by(ticker: "DTR", name: "Dynamic Trading Rights")
Crypto.find_or_create_by(ticker: "BOS", name: "BOScoin")
Crypto.find_or_create_by(ticker: "DWS", name: "DWS")
Crypto.find_or_create_by(ticker: "RNTB", name: "BitRent")
Crypto.find_or_create_by(ticker: "CND", name: "Cindicator")
Crypto.find_or_create_by(ticker: "NTK", name: "Neurotoken")
Crypto.find_or_create_by(ticker: "NKN", name: "NKN")
Crypto.find_or_create_by(ticker: "DRT", name: "DomRaider")
Crypto.find_or_create_by(ticker: "NOAH", name: "Noah Coin")
Crypto.find_or_create_by(ticker: "DRPU", name: "DCORP")
Crypto.find_or_create_by(ticker: "BMC", name: "Blackmoon")
Crypto.find_or_create_by(ticker: "BEE", name: "Bee Token")
Crypto.find_or_create_by(ticker: "BIT", name: "BitRewards")
Crypto.find_or_create_by(ticker: "ARCT", name: "Arbitrage CT")
Crypto.find_or_create_by(ticker: "SUB", name: "Substratum")
Crypto.find_or_create_by(ticker: "SPD", name: "SPINDLE")
Crypto.find_or_create_by(ticker: "LRC", name: "Loopring")
Crypto.find_or_create_by(ticker: "TKY", name: "Thekey")
Crypto.find_or_create_by(ticker: "WEB", name: "Webcoin")
Crypto.find_or_create_by(ticker: "SWTH", name: "Switcheo")
Crypto.find_or_create_by(ticker: "LEND", name: "ETHLend")
Crypto.find_or_create_by(ticker: "FTI", name: "FansTime")
Crypto.find_or_create_by(ticker: "SOUL", name: "Phantasma")
Crypto.find_or_create_by(ticker: "DAXT", name: "BlockEx")
Crypto.find_or_create_by(ticker: "ENG", name: "Enigma")
Crypto.find_or_create_by(ticker: "MYST", name: "Mysterium")
Crypto.find_or_create_by(ticker: "SS", name: "Sharder Chain")
Crypto.find_or_create_by(ticker: "IND", name: "Indorse Token")
Crypto.find_or_create_by(ticker: "DGX", name: "Digix Gold")
Crypto.find_or_create_by(ticker: "LEMO", name: "Lemo")
Crypto.find_or_create_by(ticker: "HOT", name: "Holo")
Crypto.find_or_create_by(ticker: "RDN", name: "Raiden Network Token")
Crypto.find_or_create_by(ticker: "ZRC", name: "ZrCoin")
Crypto.find_or_create_by(ticker: "ELF", name: "aelf")
Crypto.find_or_create_by(ticker: "HYDRO", name: "Hydro")
Crypto.find_or_create_by(ticker: "EVE", name: "Devery")
Crypto.find_or_create_by(ticker: "BBN", name: "Banyan Network")
Crypto.find_or_create_by(ticker: "RED", name: "RedLang")
Crypto.find_or_create_by(ticker: "AUC", name: "Auctus")
Crypto.find_or_create_by(ticker: "EVX", name: "Everex")
Crypto.find_or_create_by(ticker: "VTC", name: "Vertcoin")
Crypto.find_or_create_by(ticker: "MORE", name: "More")
Crypto.find_or_create_by(ticker: "LEDU", name: "Education Ecosystem")
Crypto.find_or_create_by(ticker: "PRO", name: "Propy")
Crypto.find_or_create_by(ticker: "DAG", name: "Constellation")
Crypto.find_or_create_by(ticker: "BCX", name: "BCX")
Crypto.find_or_create_by(ticker: "DCT", name: "DECENT")
Crypto.find_or_create_by(ticker: "BKX", name: "BANKEX")
Crypto.find_or_create_by(ticker: "CS", name: "Credits")
Crypto.find_or_create_by(ticker: "SENC", name: "Sentinel")
Crypto.find_or_create_by(ticker: "HTML", name: "HTMLCOIN")
Crypto.find_or_create_by(ticker: "INSUR", name: "InsurChain")
Crypto.find_or_create_by(ticker: "FUN", name: "FunFair")
Crypto.find_or_create_by(ticker: "LRN", name: "LRN")
Crypto.find_or_create_by(ticker: "MFTU", name: "MFTU")
Crypto.find_or_create_by(ticker: "DIM", name: "DIMCOIN")
Crypto.find_or_create_by(ticker: "BTCP", name: "Bitcoin Private")
Crypto.find_or_create_by(ticker: "OMNI", name: "Omni")
Crypto.find_or_create_by(ticker: "RMESH", name: "RightMesh")
Crypto.find_or_create_by(ticker: "ALTX", name: "Alttex")
Crypto.find_or_create_by(ticker: "XTRD", name: "XTRD")
Crypto.find_or_create_by(ticker: "CHSB", name: "SwissBorg")
Crypto.find_or_create_by(ticker: "HYPRO", name: "HYPRO")
Crypto.find_or_create_by(ticker: "TDS", name: "TokenDesk")
Crypto.find_or_create_by(ticker: "SEQ", name: "Sequence")
Crypto.find_or_create_by(ticker: "MFT", name: "Mainframe")
Crypto.find_or_create_by(ticker: "BOT", name: "Bodhi Token")
Crypto.find_or_create_by(ticker: "HERO", name: "Hero Origen")
Crypto.find_or_create_by(ticker: "KEY", name: "SelfKey")
Crypto.find_or_create_by(ticker: "QASH", name: "QASH")
Crypto.find_or_create_by(ticker: "SBTC", name: "Super Bitcoin")
Crypto.find_or_create_by(ticker: "VIBE", name: "VIBE")
Crypto.find_or_create_by(ticker: "ION", name: "ION")
Crypto.find_or_create_by(ticker: "PTOY", name: "Patientory")
Crypto.find_or_create_by(ticker: "BTG", name: "Bitcoin Gold")
Crypto.find_or_create_by(ticker: "STQ", name: "Storiqa")
Crypto.find_or_create_by(ticker: "TKA", name: "Tokia")
Crypto.find_or_create_by(ticker: "BIFI", name: "BitcoinFile")
Crypto.find_or_create_by(ticker: "TOLL", name: "BridgeProtocol")
Crypto.find_or_create_by(ticker: "GTC", name: "Game.com")
Crypto.find_or_create_by(ticker: "OLT", name: "OneLedger")
Crypto.find_or_create_by(ticker: "MITH", name: "Mithril")
Crypto.find_or_create_by(ticker: "MXM", name: "MaxiMine")
Crypto.find_or_create_by(ticker: "AMM", name: "MicroMoney")
Crypto.find_or_create_by(ticker: "XYO", name: "XY Oracle")
Crypto.find_or_create_by(ticker: "SAN", name: "Santiment Network TokenSAN")
Crypto.find_or_create_by(ticker: "IPL", name: "InsurePal")
Crypto.find_or_create_by(ticker: "GAME", name: "GameCredits")
Crypto.find_or_create_by(ticker: "MRPH", name: "Morpheus Network")
Crypto.find_or_create_by(ticker: "SEAL", name: "Seal Network")
Crypto.find_or_create_by(ticker: "COV", name: "Covesting")
Crypto.find_or_create_by(ticker: "GBX", name: "GoByte")
Crypto.find_or_create_by(ticker: "MGO", name: "MobileGo")
Crypto.find_or_create_by(ticker: "FCT", name: "Factom")
Crypto.find_or_create_by(ticker: "MEME", name: "Memetic / PepeCoin")
Crypto.find_or_create_by(ticker: "MDA", name: "Moeda Loyalty Points")
Crypto.find_or_create_by(ticker: "UQC", name: "Uquid Coin")
Crypto.find_or_create_by(ticker: "SET", name: "Swytch Energy")
Crypto.find_or_create_by(ticker: "TCT", name: "TokenClub")
Crypto.find_or_create_by(ticker: "HBT", name: "Hubiits")
Crypto.find_or_create_by(ticker: "SWT", name: "Swarm City")
Crypto.find_or_create_by(ticker: "TRUE", name: "True Chain")
Crypto.find_or_create_by(ticker: "CURE", name: "Curecoin")
Crypto.find_or_create_by(ticker: "THC", name: "HempCoin")
Crypto.find_or_create_by(ticker: "CAJ", name: "Cajutel")
Crypto.find_or_create_by(ticker: "FUEL", name: "Etherparty")
Crypto.find_or_create_by(ticker: "ANT", name: "Aragon")
Crypto.find_or_create_by(ticker: "SETH", name: "Sether")
Crypto.find_or_create_by(ticker: "CEL", name: "Celsius")
Crypto.find_or_create_by(ticker: "EDR", name: "Endor")
Crypto.find_or_create_by(ticker: "WPR", name: "WePower")
Crypto.find_or_create_by(ticker: "RCN", name: "Ripio Credit Network")
Crypto.find_or_create_by(ticker: "SLS", name: "SaluS")
Crypto.find_or_create_by(ticker: "JNT", name: "Jibrel Network Token")
Crypto.find_or_create_by(ticker: "NULS", name: "Nuls")
Crypto.find_or_create_by(ticker: "CPC", name: "CPCChain")
Crypto.find_or_create_by(ticker: "CSNO", name: "BitDice")
Crypto.find_or_create_by(ticker: "POLY", name: "Polymath")
Crypto.find_or_create_by(ticker: "ELEC", name: "ElectrifyAsia")
Crypto.find_or_create_by(ticker: "TIC", name: "Thingschain")
Crypto.find_or_create_by(ticker: "RVN", name: "RavenCoin")
Crypto.find_or_create_by(ticker: "SCC", name: "StockChain")
Crypto.find_or_create_by(ticker: "FSN", name: "Fusion")
Crypto.find_or_create_by(ticker: "SPHR", name: "Sphere")
Crypto.find_or_create_by(ticker: "FLO", name: "FlorinCoin")
Crypto.find_or_create_by(ticker: "NCASH", name: "Nucleus Vision")
Crypto.find_or_create_by(ticker: "YOYOW", name: "YOYOW")
Crypto.find_or_create_by(ticker: "NAVI", name: "Naviaddress")
Crypto.find_or_create_by(ticker: "ARN", name: "Aeron")
Crypto.find_or_create_by(ticker: "XLM", name: "Stellar")
Crypto.find_or_create_by(ticker: "BCDN", name: "BlockCDN")
Crypto.find_or_create_by(ticker: "NPXS", name: "Pundi X")
Crypto.find_or_create_by(ticker: "DCN", name: "Dentacoin")
Crypto.find_or_create_by(ticker: "CANN", name: "CannabisCoin")
Crypto.find_or_create_by(ticker: "LBA", name: "LibraCredit")
Crypto.find_or_create_by(ticker: "WAVES", name: "Waves")
Crypto.find_or_create_by(ticker: "NPX", name: "Napoleon X")
Crypto.find_or_create_by(ticker: "GAM", name: "Gambit")
Crypto.find_or_create_by(ticker: "MCO", name: "Monaco")
Crypto.find_or_create_by(ticker: "LST", name: "Lendroid")
Crypto.find_or_create_by(ticker: "ONL", name: "On.Live")
Crypto.find_or_create_by(ticker: "ENJ", name: "Enjin Coin")
Crypto.find_or_create_by(ticker: "MOD", name: "Modum")
Crypto.find_or_create_by(ticker: "VRM", name: "VeriumReserve")
Crypto.find_or_create_by(ticker: "UNC", name: "Unigame")
Crypto.find_or_create_by(ticker: "MDT", name: "MeasurableData")
Crypto.find_or_create_by(ticker: "DOGE", name: "Dogecoin")
Crypto.find_or_create_by(ticker: "ABT", name: "Arcblock")
Crypto.find_or_create_by(ticker: "SWFTC", name: "SwftCoin")
Crypto.find_or_create_by(ticker: "OIO", name: "online.io")
Crypto.find_or_create_by(ticker: "HGT", name: "HelloGold")
Crypto.find_or_create_by(ticker: "DDD", name: "Scry DDD")
Crypto.find_or_create_by(ticker: "PART", name: "Particl")
Crypto.find_or_create_by(ticker: "CPAY", name: "Cryptopay")
Crypto.find_or_create_by(ticker: "LSK", name: "Lisk")
Crypto.find_or_create_by(ticker: "QTUM", name: "Qtum")
Crypto.find_or_create_by(ticker: "BLT", name: "Bloom")
Crypto.find_or_create_by(ticker: "DYN", name: "Dynamic")
Crypto.find_or_create_by(ticker: "ROX", name: "Robotina")
Crypto.find_or_create_by(ticker: "BAT", name: "Basic Attention Token")
Crypto.find_or_create_by(ticker: "RDD", name: "ReddCoin")
Crypto.find_or_create_by(ticker: "EJOY", name: "Ether Joy")
Crypto.find_or_create_by(ticker: "BANCA", name: "Banca")
Crypto.find_or_create_by(ticker: "XVG", name: "Verge")
Crypto.find_or_create_by(ticker: "ETHOS", name: "Ethos")
Crypto.find_or_create_by(ticker: "IOP", name: "Internet of People")
Crypto.find_or_create_by(ticker: "SLR", name: "SolarCoin")
Crypto.find_or_create_by(ticker: "CENNZ", name: "Centrality")
Crypto.find_or_create_by(ticker: "SHIFT", name: "Shift")
Crypto.find_or_create_by(ticker: "ODE", name: "ODEM")
Crypto.find_or_create_by(ticker: "APPC", name: "AppCoins")
Crypto.find_or_create_by(ticker: "ETC", name: "Ethereum Classic")
Crypto.find_or_create_by(ticker: "UKG", name: "Unikoin Gold")
Crypto.find_or_create_by(ticker: "SPF", name: "SportyFi")
Crypto.find_or_create_by(ticker: "INCX", name: "InternationalCryptoX")
Crypto.find_or_create_by(ticker: "TNB", name: "Time New Bank")
Crypto.find_or_create_by(ticker: "CVCOIN", name: "CVcoin")
Crypto.find_or_create_by(ticker: "BCPT", name: "BlockMason Credit Protocol")
Crypto.find_or_create_by(ticker: "GRMD", name: "GreenMed")
Crypto.find_or_create_by(ticker: "CBT", name: "CommerceBlock")
Crypto.find_or_create_by(ticker: "NLG", name: "Gulden")
Crypto.find_or_create_by(ticker: "STU", name: "bitJob")
Crypto.find_or_create_by(ticker: "TUSD", name: "True USD")
Crypto.find_or_create_by(ticker: "WYS", name: "wys Token")
Crypto.find_or_create_by(ticker: "CMCT", name: "Crowd Machine")
Crypto.find_or_create_by(ticker: "VEE", name: "BLOCKv")
Crypto.find_or_create_by(ticker: "POWR", name: "Power Ledger")
Crypto.find_or_create_by(ticker: "GNX", name: "Ignite")
Crypto.find_or_create_by(ticker: "NANO", name: "Nano")
Crypto.find_or_create_by(ticker: "BNK", name: "Bankera")
Crypto.find_or_create_by(ticker: "ZIL", name: "Zilliqa")
Crypto.find_or_create_by(ticker: "PAT", name: "PAT")
Crypto.find_or_create_by(ticker: "SIB", name: "SIBCoin")
Crypto.find_or_create_by(ticker: "MTL", name: "Metal")
Crypto.find_or_create_by(ticker: "HYB", name: "Hybrid Block")
Crypto.find_or_create_by(ticker: "GBYTE", name: "Byteball")
Crypto.find_or_create_by(ticker: "GAS", name: "Gas")
Crypto.find_or_create_by(ticker: "BLK", name: "BlackCoin")
Crypto.find_or_create_by(ticker: "GLD", name: "GoldCoin")
Crypto.find_or_create_by(ticker: "UPP", name: "Sentinel Protocol")
Crypto.find_or_create_by(ticker: "EGC", name: "EverGreenCoin")
Crypto.find_or_create_by(ticker: "KICK", name: "KickCoin")
Crypto.find_or_create_by(ticker: "BTS", name: "BitShares")
Crypto.find_or_create_by(ticker: "B2X", name: "B2B")
Crypto.find_or_create_by(ticker: "XCP", name: "Counterparty")
Crypto.find_or_create_by(ticker: "DADI", name: "DADI")
Crypto.find_or_create_by(ticker: "GARD", name: "Hashgard")
Crypto.find_or_create_by(ticker: "S", name: "Sharpay")
Crypto.find_or_create_by(ticker: "GLA", name: "Gladius")
Crypto.find_or_create_by(ticker: "HBZ", name: "Helbiz")
Crypto.find_or_create_by(ticker: "DICE", name: "Etheroll")
Crypto.find_or_create_by(ticker: "QNTU", name: "Quanta Network Utility Token")
Crypto.find_or_create_by(ticker: "PKG", name: "PKG Token")
Crypto.find_or_create_by(ticker: "NXC", name: "Nexium")
Crypto.find_or_create_by(ticker: "LUN", name: "Lunyr")
Crypto.find_or_create_by(ticker: "XUC", name: "Exchange Union")
Crypto.find_or_create_by(ticker: "WIKI", name: "WIKI")
Crypto.find_or_create_by(ticker: "STRAT", name: "Stratis")
Crypto.find_or_create_by(ticker: "IXT", name: "iXledger")
Crypto.find_or_create_by(ticker: "OTN", name: "Open Trading Network")
Crypto.find_or_create_by(ticker: "LION", name: "CoinLion")
Crypto.find_or_create_by(ticker: "CLOAK", name: "CloakCoin")
Crypto.find_or_create_by(ticker: "DGTX", name: "DigitexFutures")
Crypto.find_or_create_by(ticker: "TKS", name: "Tokes")
Crypto.find_or_create_by(ticker: "BCH", name: "Bitcoin Cash")
Crypto.find_or_create_by(ticker: "OAX", name: "OAX")
Crypto.find_or_create_by(ticker: "DTH", name: "Dether")
Crypto.find_or_create_by(ticker: "NEBL", name: "Neblio")
Crypto.find_or_create_by(ticker: "WAN", name: "Wanchain")
Crypto.find_or_create_by(ticker: "MYB", name: "MyBit Token")
Crypto.find_or_create_by(ticker: "LDC", name: "Leadcoin")
Crypto.find_or_create_by(ticker: "ETH", name: "Ethereum")
Crypto.find_or_create_by(ticker: "IHF", name: "Invictus Hyperion")
Crypto.find_or_create_by(ticker: "POT", name: "PotCoin")
Crypto.find_or_create_by(ticker: "AVH", name: "Animation Vision Cash")
Crypto.find_or_create_by(ticker: "BITCOINUS", name: "Bitcoinus")
Crypto.find_or_create_by(ticker: "GUP", name: "Matchpool")
Crypto.find_or_create_by(ticker: "XST", name: "Stealthcoin")
Crypto.find_or_create_by(ticker: "HER", name: "HeroNode Token")
Crypto.find_or_create_by(ticker: "AXPR", name: "aXpire")
Crypto.find_or_create_by(ticker: "VET", name: "VeChain Thor")
Crypto.find_or_create_by(ticker: "CHAT", name: "ChatCoin")
Crypto.find_or_create_by(ticker: "NAV", name: "NAV Coin")
Crypto.find_or_create_by(ticker: "CLN", name: "Colu Local Network")
Crypto.find_or_create_by(ticker: "PHX", name: "Red Pulse Pheonix")
Crypto.find_or_create_by(ticker: "LOOM", name: "Loom Network")
Crypto.find_or_create_by(ticker: "AURA", name: "Aurora DAO")
Crypto.find_or_create_by(ticker: "XAUR", name: "Xaurum")
Crypto.find_or_create_by(ticker: "GXS", name: "GXShares")
Crypto.find_or_create_by(ticker: "SKM", name: "Skrumble")
Crypto.find_or_create_by(ticker: "SVD", name: "Savedroid")
Crypto.find_or_create_by(ticker: "CRPT", name: "Crypterium")
Crypto.find_or_create_by(ticker: "TDP", name: "Truedeck")
Crypto.find_or_create_by(ticker: "KWATT", name: "KWATT")
Crypto.find_or_create_by(ticker: "SPC", name: "SpaceChain")
Crypto.find_or_create_by(ticker: "HC", name: "HyperCash")
Crypto.find_or_create_by(ticker: "SC", name: "Siacoin")
Crypto.find_or_create_by(ticker: "JOT", name: "Jury.Online")
Crypto.find_or_create_by(ticker: "EOS", name: "EOS")
Crypto.find_or_create_by(ticker: "ACT", name: "Achain")
Crypto.find_or_create_by(ticker: "CRED", name: "Verify")
Crypto.find_or_create_by(ticker: "ETK", name: "EnergiToken")
Crypto.find_or_create_by(ticker: "BLZ", name: "Bluzelle")
Crypto.find_or_create_by(ticker: "REM", name: "Remme")
Crypto.find_or_create_by(ticker: "DBET", name: "DecentBet")
Crypto.find_or_create_by(ticker: "ZPT", name: "Zeepin")
Crypto.find_or_create_by(ticker: "IMT", name: "MoneyToken")
Crypto.find_or_create_by(ticker: "ZEC", name: "Zcash")
Crypto.find_or_create_by(ticker: "LBC", name: "LBRY Credits")
Crypto.find_or_create_by(ticker: "DENT", name: "Dent")
Crypto.find_or_create_by(ticker: "NAS", name: "Nebulas")
Crypto.find_or_create_by(ticker: "BNT", name: "Bancor")
Crypto.find_or_create_by(ticker: "BIO", name: "BioCrypt")
Crypto.find_or_create_by(ticker: "DLT", name: "Agrello")
Crypto.find_or_create_by(ticker: "BET", name: "DAO.Casino")
Crypto.find_or_create_by(ticker: "DTA", name: "Data")
Crypto.find_or_create_by(ticker: "STAR", name: "Starbase")
Crypto.find_or_create_by(ticker: "MEETONE", name: "MEET.ONE")
Crypto.find_or_create_by(ticker: "DPN", name: "DIPNET")
Crypto.find_or_create_by(ticker: "DOCK", name: "Dock")
Crypto.find_or_create_by(ticker: "TNT", name: "Tierion")
Crypto.find_or_create_by(ticker: "NEU", name: "Neumark")
Crypto.find_or_create_by(ticker: "GRC", name: "GridCoin")
Crypto.find_or_create_by(ticker: "ETP", name: "Metaverse ETP")
Crypto.find_or_create_by(ticker: "1ST", name: "Firstblood")
Crypto.find_or_create_by(ticker: "HAV", name: "Havven")
Crypto.find_or_create_by(ticker: "TNC", name: "Trinity")
Crypto.find_or_create_by(ticker: "UBT", name: "Unibright")
Crypto.find_or_create_by(ticker: "OMG", name: "OmiseGO")
Crypto.find_or_create_by(ticker: "FOTA", name: "Fortuna")
Crypto.find_or_create_by(ticker: "EDO", name: "Eidoo")
Crypto.find_or_create_by(ticker: "GOT", name: "GOToken")
Crypto.find_or_create_by(ticker: "FYN", name: "FundYourselfNow")
Crypto.find_or_create_by(ticker: "FXT", name: "FuzeX")
Crypto.find_or_create_by(ticker: "MVL", name: "Mass Vehicle Ledger")
Crypto.find_or_create_by(ticker: "XWC", name: "WhiteCoin")
Crypto.find_or_create_by(ticker: "RVR", name: "RevolutionVR")
Crypto.find_or_create_by(ticker: "PPC", name: "Peercoin")
Crypto.find_or_create_by(ticker: "GEO", name: "GeoCoin")
Crypto.find_or_create_by(ticker: "NIO", name: "Autonio")
Crypto.find_or_create_by(ticker: "PMNT", name: "Paymon")
Crypto.find_or_create_by(ticker: "BRD", name: "Bread")
Crypto.find_or_create_by(ticker: "OPT", name: "Opus")
Crypto.find_or_create_by(ticker: "TIME", name: "Chronobank")
Crypto.find_or_create_by(ticker: "BUBO", name: "Budbo")
Crypto.find_or_create_by(ticker: "ICX", name: "ICON")
Crypto.find_or_create_by(ticker: "EXCL", name: "ExclusiveCoin")
Crypto.find_or_create_by(ticker: "ATMI", name: "Atonomi")
Crypto.find_or_create_by(ticker: "BCDT", name: "BCDiploma")
Crypto.find_or_create_by(ticker: "FCN", name: "Fantomcoin")
Crypto.find_or_create_by(ticker: "ABS", name: "Absolute Coin")
Crypto.find_or_create_by(ticker: "R", name: "Revain")
Crypto.find_or_create_by(ticker: "DTB", name: "Databits")
Crypto.find_or_create_by(ticker: "ORME", name: "Ormeus Coin")
Crypto.find_or_create_by(ticker: "BAX", name: "BABB")
Crypto.find_or_create_by(ticker: "WILD", name: "Wild Crypto")
Crypto.find_or_create_by(ticker: "MESSE", name: "MesseToken")
Crypto.find_or_create_by(ticker: "ZCN", name: "0chain")
Crypto.find_or_create_by(ticker: "GVT", name: "Genesis Vision")
Crypto.find_or_create_by(ticker: "NANJ", name: "NANJCOIN")
Crypto.find_or_create_by(ticker: "NLC2", name: "NoLimitCoin")
Crypto.find_or_create_by(ticker: "HIRE", name: "HireMatch")
Crypto.find_or_create_by(ticker: "BCD", name: "Bitcoin Diamond")
Crypto.find_or_create_by(ticker: "RVT", name: "Rivetz")
Crypto.find_or_create_by(ticker: "NPLC", name: "PlusCoin")
Crypto.find_or_create_by(ticker: "CPY", name: "COPYTRACK")
Crypto.find_or_create_by(ticker: "EMC", name: "Emercoin")
Crypto.find_or_create_by(ticker: "BFT", name: "BnkToTheFuture")
Crypto.find_or_create_by(ticker: "STX", name: "Stox")
Crypto.find_or_create_by(ticker: "KNC", name: "Kyber Network")
Crypto.find_or_create_by(ticker: "LCC", name: "Litecoin Cash")
Crypto.find_or_create_by(ticker: "AMB", name: "Ambrosus")
Crypto.find_or_create_by(ticker: "SMT", name: "SmartMesh")
Crypto.find_or_create_by(ticker: "ABY", name: "ArtByte")
Crypto.find_or_create_by(ticker: "USNBT", name: "NuBits")
Crypto.find_or_create_by(ticker: "LNC", name: "Blocklancer")
Crypto.find_or_create_by(ticker: "XMC", name: "Monero Classic")
Crypto.find_or_create_by(ticker: "OK", name: "OKCash")
Crypto.find_or_create_by(ticker: "DRGN", name: "Dragonchain")
Crypto.find_or_create_by(ticker: "AVINOC", name: "AVINOC")
Crypto.find_or_create_by(ticker: "FTT", name: "Farmatrust")
Crypto.find_or_create_by(ticker: "STAK", name: "STRAKS")
Crypto.find_or_create_by(ticker: "DAV", name: "DAV Network")
Crypto.find_or_create_by(ticker: "STORJ", name: "Storj")
Crypto.find_or_create_by(ticker: "CSM", name: "Consentium")
Crypto.find_or_create_by(ticker: "COVAL", name: "Circuits of Value")
Crypto.find_or_create_by(ticker: "REP", name: "Augur")
Crypto.find_or_create_by(ticker: "SENSE", name: "SENSE")
Crypto.find_or_create_by(ticker: "NXS", name: "Nexus")
Crypto.find_or_create_by(ticker: "SIG", name: "Spectiv")
Crypto.find_or_create_by(ticker: "AVT", name: "Aventus")
Crypto.find_or_create_by(ticker: "BRK", name: "Breakout")
Crypto.find_or_create_by(ticker: "SOP", name: "SoPay")
Crypto.find_or_create_by(ticker: "XMO", name: "Monero Original")
Crypto.find_or_create_by(ticker: "RLX", name: "Relex")
Crypto.find_or_create_by(ticker: "GEN", name: "DAOstack")
Crypto.find_or_create_by(ticker: "NGC", name: "NAGA")
Crypto.find_or_create_by(ticker: "CVC", name: "Civic")
Crypto.find_or_create_by(ticker: "NCT", name: "PolySwarm")
Crypto.find_or_create_by(ticker: "THRT", name: "Thrive Token")
Crypto.find_or_create_by(ticker: "XES", name: "PROXEUS")
Crypto.find_or_create_by(ticker: "BITX", name: "BitScreenerToken")
Crypto.find_or_create_by(ticker: "MUE", name: "MonetaryUnit")
Crypto.find_or_create_by(ticker: "CST", name: "CryptosolarTech")
Crypto.find_or_create_by(ticker: "ARDR", name: "Ardor")
Crypto.find_or_create_by(ticker: "ABYSS", name: "The Abyss")
Crypto.find_or_create_by(ticker: "VIB", name: "Viberate")
Crypto.find_or_create_by(ticker: "METM", name: "MetaMorph")
Crypto.find_or_create_by(ticker: "CHP", name: "CoinPoker")
Crypto.find_or_create_by(ticker: "ZCO", name: "Zebi Coin")
Crypto.find_or_create_by(ticker: "PASC", name: "Pascal Coin")
Crypto.find_or_create_by(ticker: "DOR", name: "Dorado")
Crypto.find_or_create_by(ticker: "PXG", name: "PlayGame")
Crypto.find_or_create_by(ticker: "UTK", name: "Utrust")
Crypto.find_or_create_by(ticker: "QSP", name: "Quantstamp")
Crypto.find_or_create_by(ticker: "HPC", name: "HappyCoin")
Crypto.find_or_create_by(ticker: "VLD", name: "Vetri")
Crypto.find_or_create_by(ticker: "XRA", name: "Xriba")
Crypto.find_or_create_by(ticker: "BBK", name: "Brickblock")
Crypto.find_or_create_by(ticker: "DAY", name: "Chronologic")
Crypto.find_or_create_by(ticker: "RPM", name: "Render Payment")
Crypto.find_or_create_by(ticker: "SKIN", name: "SkinCoin")
Crypto.find_or_create_by(ticker: "BDG", name: "BitDegree")
Crypto.find_or_create_by(ticker: "GTO", name: "Gifto")
Crypto.find_or_create_by(ticker: "DROP", name: "Dropil")
Crypto.find_or_create_by(ticker: "CEEK", name: "CEEK")
Crypto.find_or_create_by(ticker: "FTM", name: "Fantom")
Crypto.find_or_create_by(ticker: "MUSIC", name: "Musicoin")
Crypto.find_or_create_by(ticker: "SNM", name: "SONM")
Crypto.find_or_create_by(ticker: "MAID", name: "MaidSafeCoin")
Crypto.find_or_create_by(ticker: "AST", name: "AirSwap")
Crypto.find_or_create_by(ticker: "FREC", name: "Freyrchain")
Crypto.find_or_create_by(ticker: "DOVU", name: "Dovu")
Crypto.find_or_create_by(ticker: "BURST", name: "Burst")
Crypto.find_or_create_by(ticker: "DOPE", name: "DopeCoin")
Crypto.find_or_create_by(ticker: "SUR", name: "Suretly")
Crypto.find_or_create_by(ticker: "IGNIS", name: "Ignis")
Crypto.find_or_create_by(ticker: "HAVY", name: "Havy")
Crypto.find_or_create_by(ticker: "PYN", name: "Paycent")
Crypto.find_or_create_by(ticker: "MORPH", name: "Morpheus Network")
Crypto.find_or_create_by(ticker: "WAX", name: "WAX")
Crypto.find_or_create_by(ticker: "CCL", name: "CyClean")
Crypto.find_or_create_by(ticker: "AGI", name: "SingularityNET")
Crypto.find_or_create_by(ticker: "REX", name: "Imbrex")
Crypto.find_or_create_by(ticker: "SYS", name: "Syscoin")
Crypto.find_or_create_by(ticker: "BNTY", name: "Bounty0x")
Crypto.find_or_create_by(ticker: "PINK", name: "PinkCoin")
Crypto.find_or_create_by(ticker: "SEN", name: "Consensus")
Crypto.find_or_create_by(ticker: "PRE", name: "PRCoin")
Crypto.find_or_create_by(ticker: "XEM", name: "NEM")
Crypto.find_or_create_by(ticker: "ADH", name: "AdHive")
Crypto.find_or_create_by(ticker: "TRAC", name: "OriginTrail")
Crypto.find_or_create_by(ticker: "NCC", name: "NeuroChain")
Crypto.find_or_create_by(ticker: "BOXX", name: "Blockparty")
Crypto.find_or_create_by(ticker: "MER", name: "Mercury")
Crypto.find_or_create_by(ticker: "TAU", name: "Lamden")
Crypto.find_or_create_by(ticker: "CAS", name: "Cashaa")
Crypto.find_or_create_by(ticker: "BCI", name: "Bitcoin Interest")
Crypto.find_or_create_by(ticker: "BTT", name: "Blocktrade Token")
Crypto.find_or_create_by(ticker: "XNK", name: "Ink Protocol")
Crypto.find_or_create_by(ticker: "BU", name: "Bumo")
Crypto.find_or_create_by(ticker: "GRS", name: "Groestlcoin")
Crypto.find_or_create_by(ticker: "THETA", name: "Theta Token")
Crypto.find_or_create_by(ticker: "GEM", name: "Gems")
Crypto.find_or_create_by(ticker: "KRL", name: "Kryll")
Crypto.find_or_create_by(ticker: "CRW", name: "Crown")
Crypto.find_or_create_by(ticker: "NEOS", name: "NeosCoin")
Crypto.find_or_create_by(ticker: "NDC", name: "NEVERDIE")
Crypto.find_or_create_by(ticker: "HMQ", name: "Humaniq")
Crypto.find_or_create_by(ticker: "VRC", name: "VeriCoin")
Crypto.find_or_create_by(ticker: "EPY", name: "Emphy")
Crypto.find_or_create_by(ticker: "CLAM", name: "Clams")
Crypto.find_or_create_by(ticker: "HOLD", name: "HOLD")
Crypto.find_or_create_by(ticker: "GSE", name: "GSENetwork")
Crypto.find_or_create_by(ticker: "TUBE", name: "BitTube")
Crypto.find_or_create_by(ticker: "TOMO", name: "TomoChain")
Crypto.find_or_create_by(ticker: "LUC", name: "Level Up Coin")
Crypto.find_or_create_by(ticker: "TTU", name: "TaTaTu")
Crypto.find_or_create_by(ticker: "PMA", name: "PumaPay")
Crypto.find_or_create_by(ticker: "LA", name: "LAToken")
Crypto.find_or_create_by(ticker: "PIX", name: "Lampix")
Crypto.find_or_create_by(ticker: "TCN", name: "TCoin")
Crypto.find_or_create_by(ticker: "OST", name: "Simple Token")
Crypto.find_or_create_by(ticker: "MANA", name: "Decentraland")
Crypto.find_or_create_by(ticker: "XMR", name: "Monero")
Crypto.find_or_create_by(ticker: "TRX", name: "TRON")
Crypto.find_or_create_by(ticker: "SNGLS", name: "SingularDTV")
Crypto.find_or_create_by(ticker: "GNT", name: "Golem")
Crypto.find_or_create_by(ticker: "MONA", name: "MonaCoin")
Crypto.find_or_create_by(ticker: "VOCO", name: "Provoco")
Crypto.find_or_create_by(ticker: "AMN", name: "Amon")
Crypto.find_or_create_by(ticker: "QNT", name: "Quant")
Crypto.find_or_create_by(ticker: "MITX", name: "Morpheus Labs")
Crypto.find_or_create_by(ticker: "BZNT", name: "Bezant")
Crypto.find_or_create_by(ticker: "ADX", name: "AdEx")
Crypto.find_or_create_by(ticker: "STORM", name: "Storm")
Crypto.find_or_create_by(ticker: "SEELE", name: "Seele")
Crypto.find_or_create_by(ticker: "TKN", name: "TokenCard")
Crypto.find_or_create_by(ticker: "EBST", name: "eBoost")
Crypto.find_or_create_by(ticker: "PCL", name: "Peculium")
Crypto.find_or_create_by(ticker: "POA", name: "POA Network")
Crypto.find_or_create_by(ticker: "MSP", name: "Mothership")
Crypto.find_or_create_by(ticker: "BERRY", name: "Rentberry")
Crypto.find_or_create_by(ticker: "BETR", name: "BetterBetting")
Crypto.find_or_create_by(ticker: "BTX", name: "Bitcore")
Crypto.find_or_create_by(ticker: "MLN", name: "Melon")
Crypto.find_or_create_by(ticker: "PDX", name: "PDX")
Crypto.find_or_create_by(ticker: "OCN", name: "Odyssey")
Crypto.find_or_create_by(ticker: "FLDC", name: "FoldingCoin")
Crypto.find_or_create_by(ticker: "MET", name: "Metronome")
Crypto.find_or_create_by(ticker: "BOX", name: "Contentbox")
Crypto.find_or_create_by(ticker: "MKR", name: "Maker")
Crypto.find_or_create_by(ticker: "DASH", name: "Dash")
Crypto.find_or_create_by(ticker: "ICN", name: "Iconomi")
Crypto.find_or_create_by(ticker: "WIZ", name: "CrowdWiz")
Crypto.find_or_create_by(ticker: "IQ", name: "Everipedia")
Crypto.find_or_create_by(ticker: "QKC", name: "QuarkChain")
Crypto.find_or_create_by(ticker: "SKCH", name: "Skychain Global Token")
Crypto.find_or_create_by(ticker: "LINK", name: "ChainLink")
Crypto.find_or_create_by(ticker: "DNT", name: "district0x")
Crypto.find_or_create_by(ticker: "INCNT", name: "Incent")
Crypto.find_or_create_by(ticker: "XMY", name: "Myriad")
Crypto.find_or_create_by(ticker: "IDH", name: "indaHash")
Crypto.find_or_create_by(ticker: "XPM", name: "Primecoin")
Crypto.find_or_create_by(ticker: "LEV", name: "LeverJ")
Crypto.find_or_create_by(ticker: "LOC", name: "LockChain")
Crypto.find_or_create_by(ticker: "FND", name: "FundRequest")
Crypto.find_or_create_by(ticker: "GOD", name: "BitcoinGod")
Crypto.find_or_create_by(ticker: "DNA", name: "Gene-Chain Coin")
Crypto.find_or_create_by(ticker: "TAAS", name: "TaaS")
Crypto.find_or_create_by(ticker: "SRN", name: "SIRIN LABS Token")
Crypto.find_or_create_by(ticker: "BTO", name: "Bottos")
Crypto.find_or_create_by(ticker: "GOLOS", name: "Golos")
Crypto.find_or_create_by(ticker: "CYFM", name: "CyberFM")
Crypto.find_or_create_by(ticker: "DBC", name: "DeepBrain Wallet")
Crypto.find_or_create_by(ticker: "PFR", name: "PayFair")
Crypto.find_or_create_by(ticker: "ZEN", name: "ZenCash")
Crypto.find_or_create_by(ticker: "CAT", name: "Catcoin")
Crypto.find_or_create_by(ticker: "LYM", name: "Lympo")
Crypto.find_or_create_by(ticker: "FSBT", name: "Forty Seven Bank Token")
Crypto.find_or_create_by(ticker: "MTH", name: "Monetha")
Crypto.find_or_create_by(ticker: "ONT", name: "Ontology")
Crypto.find_or_create_by(ticker: "IVY", name: "Ivy")
Crypto.find_or_create_by(ticker: "ODN", name: "Obsidian")
Crypto.find_or_create_by(ticker: "FOAM", name: "FOAM Token")
Crypto.find_or_create_by(ticker: "LTC", name: "Litecoin")
Crypto.find_or_create_by(ticker: "EMC2", name: "Einsteinium")
Crypto.find_or_create_by(ticker: "XDCE", name: "XDCE")
Crypto.find_or_create_by(ticker: "NEC", name: "Nectar")
Crypto.find_or_create_by(ticker: "HQX", name: "HOQU")
Crypto.find_or_create_by(ticker: "FYP", name: "FlypMe")
Crypto.find_or_create_by(ticker: "NMC", name: "NameCoin")
Crypto.find_or_create_by(ticker: "INDI", name: "India Coin")
Crypto.find_or_create_by(ticker: "SCL", name: "Sociall")
Crypto.find_or_create_by(ticker: "MAN", name: "Matrix AI Network")
Crypto.find_or_create_by(ticker: "TGAME", name: "Truegame")
Crypto.find_or_create_by(ticker: "TFD", name: "TE-FOOD")
Crypto.find_or_create_by(ticker: "UBQ", name: "Ubiq")
Crypto.find_or_create_by(ticker: "SPANK", name: "SpankChain")
Crypto.find_or_create_by(ticker: "HUC", name: "HunterCoin")
Crypto.find_or_create_by(ticker: "BAY", name: "BitBay")
Crypto.find_or_create_by(ticker: "RADS", name: "Radium")
Crypto.find_or_create_by(ticker: "ADA", name: "Cardano")
Crypto.find_or_create_by(ticker: "CNX", name: "Cryptonex")
Crypto.find_or_create_by(ticker: "WINGS", name: "Wings")
Crypto.find_or_create_by(ticker: "DMT", name: "DMarket")
Crypto.find_or_create_by(ticker: "ZAP", name: "Zap Token")
Crypto.find_or_create_by(ticker: "SENT", name: "Sentinel")
Crypto.find_or_create_by(ticker: "BBO", name: "Bigbom")
Crypto.find_or_create_by(ticker: "PAY", name: "TenX")
Crypto.find_or_create_by(ticker: "EKO", name: "EchoLink")
Crypto.find_or_create_by(ticker: "BXC", name: "BonusCloud")
Crypto.find_or_create_by(ticker: "WRC", name: "Worldcore")
Crypto.find_or_create_by(ticker: "ZCL", name: "ZClassic")
Crypto.find_or_create_by(ticker: "REQ", name: "Request Network")
Crypto.find_or_create_by(ticker: "ARK", name: "Ark")
Crypto.find_or_create_by(ticker: "KAYA", name: "KAYA Token")
Crypto.find_or_create_by(ticker: "IOTX", name: "IoTeX")
Crypto.find_or_create_by(ticker: "IOC", name: "I/O Coin")
Crypto.find_or_create_by(ticker: "DATX", name: "DATx")
Crypto.find_or_create_by(ticker: "SGN", name: "Signals Network")
Crypto.find_or_create_by(ticker: "DCR", name: "Decred")
Crypto.find_or_create_by(ticker: "PAL", name: "PolicyPal")
Crypto.find_or_create_by(ticker: "DRG", name: "DRAGON")
Crypto.find_or_create_by(ticker: "REN", name: "Republic Token")
Crypto.find_or_create_by(ticker: "BCN", name: "Bytecoin")
Crypto.find_or_create_by(ticker: "GBG", name: "GoldBlocks")
Crypto.find_or_create_by(ticker: "POE", name: "Po.et")
Crypto.find_or_create_by(ticker: "FLP", name: "FLIP")
Crypto.find_or_create_by(ticker: "AUTO", name: "CUBE")
Crypto.find_or_create_by(ticker: "TIX", name: "Blocktix")
Crypto.find_or_create_by(ticker: "EZT", name: "EZToken")
Crypto.find_or_create_by(ticker: "XEL", name: "Elastic")
Crypto.find_or_create_by(ticker: "BLOCK", name: "Blocknet")
Crypto.find_or_create_by(ticker: "EDN", name: "EdenCoin")
Crypto.find_or_create_by(ticker: "XDN", name: "DigitalNote")
Crypto.find_or_create_by(ticker: "CDT", name: "CoinDash")
Crypto.find_or_create_by(ticker: "GO", name: "GoChain")
Crypto.find_or_create_by(ticker: "2GIVE", name: "2GIVE")
Crypto.find_or_create_by(ticker: "MTN", name: "Medicalchain")
Crypto.find_or_create_by(ticker: "YCC", name: "Yuan Chain")
Crypto.find_or_create_by(ticker: "ATP", name: "AtlasProtocol")
Crypto.find_or_create_by(ticker: "RLC", name: "iExec RLC")
Crypto.find_or_create_by(ticker: "NIM", name: "Nimiq")
Crypto.find_or_create_by(ticker: "ORS", name: "ORS Group")
Crypto.find_or_create_by(ticker: "AION", name: "Aion")
Crypto.find_or_create_by(ticker: "GRID", name: "Grid+")
Crypto.find_or_create_by(ticker: "KORE", name: "Kore")
Crypto.find_or_create_by(ticker: "BOE", name: "BodhiEthereum")
Crypto.find_or_create_by(ticker: "TX", name: "TransferCoin")
Crypto.find_or_create_by(ticker: "XCLR", name: "ClearCoin")
Crypto.find_or_create_by(ticker: "DGD", name: "DigixDAO")
Crypto.find_or_create_by(ticker: "ECOM", name: "Omnitude")
Crypto.find_or_create_by(ticker: "AMP", name: "Synereo")
Crypto.find_or_create_by(ticker: "WABI", name: "WaBi")
Crypto.find_or_create_by(ticker: "NEO", name: "NEO")
Crypto.find_or_create_by(ticker: "DGB", name: "DigiByte")
Crypto.find_or_create_by(ticker: "TEL", name: "Telcoin")
Crypto.find_or_create_by(ticker: "SNTR", name: "SilentNotary")
Crypto.find_or_create_by(ticker: "PLBT", name: "Polybius")
Crypto.find_or_create_by(ticker: "COIN", name: "Coinvest")
Crypto.find_or_create_by(ticker: "PKT", name: "Playkey")
Crypto.find_or_create_by(ticker: "BLUE", name: "Ethereum Blue")
Crypto.find_or_create_by(ticker: "KBC", name: "KaratBank")
Crypto.find_or_create_by(ticker: "UTT", name: "United Traders Token")
Crypto.find_or_create_by(ticker: "CBC", name: "CashBet")
Crypto.find_or_create_by(ticker: "MWAT", name: "RED MWAT")
Crypto.find_or_create_by(ticker: "DAN", name: "Daneel")
Crypto.find_or_create_by(ticker: "HSC", name: "Hashcoin")
Crypto.find_or_create_by(ticker: "SBD", name: "Steem Backed Dollars")
Crypto.find_or_create_by(ticker: "PNT", name: "Penta")
Crypto.find_or_create_by(ticker: "COFI", name: "CoinFi")
Crypto.find_or_create_by(ticker: "KIND", name: "Kind Ads")
Crypto.find_or_create_by(ticker: "CTX", name: "CarTaxi Token")
Crypto.find_or_create_by(ticker: "COU", name: "Couchain")
Crypto.find_or_create_by(ticker: "NEXO", name: "Nexo")
Crypto.find_or_create_by(ticker: "DAI", name: "Dai")
Crypto.find_or_create_by(ticker: "ADT", name: "adToken")
Crypto.find_or_create_by(ticker: "MDS", name: "Medishares")
Crypto.find_or_create_by(ticker: "ETN", name: "Electroneum")
Crypto.find_or_create_by(ticker: "ACAT", name: "Alphacat")
Crypto.find_or_create_by(ticker: "HVN", name: "Hive")
Crypto.find_or_create_by(ticker: "BMH", name: "BlockMesh")
Crypto.find_or_create_by(ticker: "DX", name: "DxChain")
Crypto.find_or_create_by(ticker: "VME", name: "VeriME")
Crypto.find_or_create_by(ticker: "EXP", name: "Expanse")
Crypto.find_or_create_by(ticker: "EDG", name: "Edgeless")
Crypto.find_or_create_by(ticker: "VIU", name: "Viuly")
Crypto.find_or_create_by(ticker: "PNK", name: "Kleros")
Crypto.find_or_create_by(ticker: "QRL", name: "Quantum Resistant Ledger")
Crypto.find_or_create_by(ticker: "XTZ", name: "Tezos")
Crypto.find_or_create_by(ticker: "ITT", name: "ITT")
Crypto.find_or_create_by(ticker: "FTX", name: "FintruX Network")
Crypto.find_or_create_by(ticker: "LIFE", name: "LIFE")
Crypto.find_or_create_by(ticker: "USDC", name: "USD Coin")
Crypto.find_or_create_by(ticker: "CBOX", name: "CBOX")
Crypto.find_or_create_by(ticker: "CTXC", name: "Cortex")
Crypto.find_or_create_by(ticker: "CAPP", name: "Cappasity")
Crypto.find_or_create_by(ticker: "COB", name: "Cobinhood")
Crypto.find_or_create_by(ticker: "CV", name: "CarVertical")
Crypto.find_or_create_by(ticker: "CYMT", name: "CyberMusic")
Crypto.find_or_create_by(ticker: "EBC", name: "EBCoin")
Crypto.find_or_create_by(ticker: "EGT", name: "Egretia")
Crypto.find_or_create_by(ticker: "FT", name: "Fabric Token")
Crypto.find_or_create_by(ticker: "GUSD", name: "GUSD")
Crypto.find_or_create_by(ticker: "ICNQ", name: "Iconiq Lab Token")
Crypto.find_or_create_by(ticker: "MNX", name: "Minexcoin")
Crypto.find_or_create_by(ticker: "REBL", name: "Rebellious")
Crypto.find_or_create_by(ticker: "RPL", name: "Rocket Pool")
Crypto.find_or_create_by(ticker: "SAL", name: "SALPay")
Crypto.find_or_create_by(ticker: "SNET", name: "Snetwork")
Crypto.find_or_create_by(ticker: "SPND", name: "Spendcoin")
Crypto.find_or_create_by(ticker: "STK", name: "STACK")
Crypto.find_or_create_by(ticker: "SURE", name: "Surety Token")
Crypto.find_or_create_by(ticker: "TTV", name: "Token for Television")
Crypto.find_or_create_by(ticker: "UCN", name: "UChain Token")
Crypto.find_or_create_by(ticker: "XCD", name: "Capdax")
Crypto.find_or_create_by(ticker: "COSM", name: "Cosmochain")
Crypto.find_or_create_by(ticker: "ALIS", name: "ALIS Media")
Crypto.find_or_create_by(ticker: "BWX", name: "BlueWhaleToken")
Crypto.find_or_create_by(ticker: "TRST", name: "WeTrust")
Crypto.find_or_create_by(ticker: "USE", name: "Usechain")
Crypto.find_or_create_by(ticker: "EXMR", name: "EXMR")
Crypto.find_or_create_by(ticker: "EXY", name: "Experty")
Crypto.find_or_create_by(ticker: "GST", name: "Game Stars")
Crypto.find_or_create_by(ticker: "FMF", name: "Formosa Financial")
Crypto.find_or_create_by(ticker: "PROC", name: "ProCurrency")
Crypto.find_or_create_by(ticker: "WAND", name: "WANDX")
Crypto.find_or_create_by(ticker: "APIS", name: "APIS")
Crypto.find_or_create_by(ticker: "BEAT", name: "BEAT")
Crypto.find_or_create_by(ticker: "BOB", name: "Bobs Repair")
Crypto.find_or_create_by(ticker: "BPT", name: "Blockport")
Crypto.find_or_create_by(ticker: "ERO", name: "Eroscoin")
Crypto.find_or_create_by(ticker: "INSTAR", name: "Insights Network")
Crypto.find_or_create_by(ticker: "MTRC", name: "ModulTrade")
Crypto.find_or_create_by(ticker: "NBAI", name: "NebulaAI")
Crypto.find_or_create_by(ticker: "PARETO", name: "Pareto Network")
Crypto.find_or_create_by(ticker: "REAL", name: "Real.Markets")
Crypto.find_or_create_by(ticker: "RHOC", name: "RHOC")
Crypto.find_or_create_by(ticker: "SAT", name: "Satisfaction Token")
Crypto.find_or_create_by(ticker: "SOC", name: "All Sports Coin")
Crypto.find_or_create_by(ticker: "SXUT", name: "Spectre U-Token")
Crypto.find_or_create_by(ticker: "WT", name: "WeToken")
Crypto.find_or_create_by(ticker: "X8X", name: "X8X Token")
Crypto.find_or_create_by(ticker: "ZIPT", name: "Zippie")
Crypto.find_or_create_by(ticker: "ASTRO", name: "AstroTokens")
Crypto.find_or_create_by(ticker: "BBC", name: "B2Bcoin")
Crypto.find_or_create_by(ticker: "C8", name: "Carboneum")
Crypto.find_or_create_by(ticker: "CARD", name: "Cardstack")
Crypto.find_or_create_by(ticker: "CXO", name: "CargoX")
Crypto.find_or_create_by(ticker: "DFS", name: "Digital Fantasy Sports")
Crypto.find_or_create_by(ticker: "DML", name: "DecentralizedML")
Crypto.find_or_create_by(ticker: "FKX", name: "KnoxsterToken")
Crypto.find_or_create_by(ticker: "HSR", name: "Hshare")
Crypto.find_or_create_by(ticker: "IDXM", name: "IDEX Membership")
Crypto.find_or_create_by(ticker: "ING", name: "Iungo")
Crypto.find_or_create_by(ticker: "IPSX", name: "IP Exchange")
Crypto.find_or_create_by(ticker: "IQN", name: "IQeon")
Crypto.find_or_create_by(ticker: "ORI", name: "Origami Network")
Crypto.find_or_create_by(ticker: "VIEW", name: "Viewly")
Crypto.find_or_create_by(ticker: "WISH", name: "MyWish")
Crypto.find_or_create_by(ticker: "FLUZ", name: "Fluz")
Crypto.find_or_create_by(ticker: "HKN", name: "HACKEN")
Crypto.find_or_create_by(ticker: "VITE", name: "VITE")
Crypto.find_or_create_by(ticker: "ACC", name: "Accelerator")
Crypto.find_or_create_by(ticker: "ARY", name: "Blockarray")
Crypto.find_or_create_by(ticker: "BNN", name: "BrokerNekoNetwork")
Crypto.find_or_create_by(ticker: "DAT", name: "Datum")
Crypto.find_or_create_by(ticker: "AIX", name: "Aigang")
Crypto.find_or_create_by(ticker: "SNOV", name: "Snovio")
Crypto.find_or_create_by(ticker: "UBC", name: "Ubcoin")
Crypto.find_or_create_by(ticker: "EXN", name: "ExchangeN")
Crypto.find_or_create_by(ticker: "ZXC", name: "0xcert Protocol")
Crypto.find_or_create_by(ticker: "CMS", name: "COMSA")
Crypto.find_or_create_by(ticker: "DXT", name: "DataWallet Token")
Crypto.find_or_create_by(ticker: "GIM", name: "Gimli")
Crypto.find_or_create_by(ticker: "ONG", name: "onG.social")
Crypto.find_or_create_by(ticker: "ABX", name: "ABX Token")
Crypto.find_or_create_by(ticker: "ERT", name: "eSports")
Crypto.find_or_create_by(ticker: "AMO", name: "AMO Coin")
Crypto.find_or_create_by(ticker: "CLO", name: "CLO")
Crypto.find_or_create_by(ticker: "CVH", name: "Curriculum Vitae")
Crypto.find_or_create_by(ticker: "INXT", name: "Internxt")
Crypto.find_or_create_by(ticker: "LPT", name: "LPT")
Crypto.find_or_create_by(ticker: "MOT", name: "Mount Olympus Token")
Crypto.find_or_create_by(ticker: "PCO", name: "Pecunio")
Crypto.find_or_create_by(ticker: "SHP", name: "Sharpe Token")
Crypto.find_or_create_by(ticker: "UET", name: "Useless Ethereum Token")
Crypto.find_or_create_by(ticker: "VIKKY", name: "Vikky")
Crypto.find_or_create_by(ticker: "ELI", name: "EligmaToken")
Crypto.find_or_create_by(ticker: "ITC", name: "IoT Chain")
Crypto.find_or_create_by(ticker: "LALA", name: "LALA")
Crypto.find_or_create_by(ticker: "OMX", name: "Omix")
Crypto.find_or_create_by(ticker: "ABLX", name: "ABLE")
Crypto.find_or_create_by(ticker: "NEXT", name: "NEXT.exchange")
Crypto.find_or_create_by(ticker: "ZPR", name: "ZPER")
Crypto.find_or_create_by(ticker: "IG", name: "IG")
Crypto.find_or_create_by(ticker: "MBRS", name: "Embers")
Crypto.find_or_create_by(ticker: "REF", name: "RefToken")
Crypto.find_or_create_by(ticker: "TALAO", name: "TALAO")
Crypto.find_or_create_by(ticker: "TTC", name: "TTC Protocol")
Crypto.find_or_create_by(ticker: "ELY", name: "Elysian")
Crypto.find_or_create_by(ticker: "SCRL", name: "Scroll")
Crypto.find_or_create_by(ticker: "SCT", name: "Soma Community Token")
Crypto.find_or_create_by(ticker: "LOCI", name: "LOCIcoin")
Crypto.find_or_create_by(ticker: "CRC", name: "Crycash")
Crypto.find_or_create_by(ticker: "ADB", name: "Adbank")
Crypto.find_or_create_by(ticker: "DELTA", name: "DeltaChain")
Crypto.find_or_create_by(ticker: "B2G", name: "Bitcoiin2Gen")
Crypto.find_or_create_by(ticker: "ESZ", name: "ESZCoin")
Crypto.find_or_create_by(ticker: "XOV", name: "XOVBank")
Crypto.find_or_create_by(ticker: "AUN", name: "Authoreon")
Crypto.find_or_create_by(ticker: "LIKE", name: "LikeCoin")
Crypto.find_or_create_by(ticker: "EURS", name: "EURS")
Crypto.find_or_create_by(ticker: "MOC", name: "Mossland")
Crypto.find_or_create_by(ticker: "CNYX", name: "CNYX")
Crypto.find_or_create_by(ticker: "EURT", name: "Tether Euro")
Crypto.find_or_create_by(ticker: "GRIN", name: "Grin")
Crypto.find_or_create_by(ticker: "MIRO", name: "Mirocana")
Crypto.find_or_create_by(ticker: "SNBL", name: "Snowball")
Crypto.find_or_create_by(ticker: "TXN", name: "Traxion")
Crypto.find_or_create_by(ticker: "VAI", name: "VIOLET")
Crypto.find_or_create_by(ticker: "VEO", name: "Amoveo")
Crypto.find_or_create_by(ticker: "TBE", name: "TowerBee")

Fiat.find_or_create_by(ticker: "AED")
Fiat.find_or_create_by(ticker: "AFN")
Fiat.find_or_create_by(ticker: "ALL")
Fiat.find_or_create_by(ticker: "AMD")
Fiat.find_or_create_by(ticker: "ANG")
Fiat.find_or_create_by(ticker: "AOA")
Fiat.find_or_create_by(ticker: "ARS")
Fiat.find_or_create_by(ticker: "AUD")
Fiat.find_or_create_by(ticker: "AVAX")
Fiat.find_or_create_by(ticker: "AWG")
Fiat.find_or_create_by(ticker: "AZN")
Fiat.find_or_create_by(ticker: "BAM")
Fiat.find_or_create_by(ticker: "BBD")
Fiat.find_or_create_by(ticker: "BDT")
Fiat.find_or_create_by(ticker: "BGN")
Fiat.find_or_create_by(ticker: "BHD")
Fiat.find_or_create_by(ticker: "BIF")
Fiat.find_or_create_by(ticker: "BMD")
Fiat.find_or_create_by(ticker: "BNB")
Fiat.find_or_create_by(ticker: "BND")
Fiat.find_or_create_by(ticker: "BOB")
Fiat.find_or_create_by(ticker: "BRL")
Fiat.find_or_create_by(ticker: "BSD")
Fiat.find_or_create_by(ticker: "BTC")
Fiat.find_or_create_by(ticker: "BTN")
Fiat.find_or_create_by(ticker: "BUSD")
Fiat.find_or_create_by(ticker: "BWP")
Fiat.find_or_create_by(ticker: "BYN")
Fiat.find_or_create_by(ticker: "BYR")
Fiat.find_or_create_by(ticker: "BZD")
Fiat.find_or_create_by(ticker: "CAD")
Fiat.find_or_create_by(ticker: "CDF")
Fiat.find_or_create_by(ticker: "CELO")
Fiat.find_or_create_by(ticker: "CHF")
Fiat.find_or_create_by(ticker: "CHZ")
Fiat.find_or_create_by(ticker: "CLF")
Fiat.find_or_create_by(ticker: "CLP")
Fiat.find_or_create_by(ticker: "CNY")
Fiat.find_or_create_by(ticker: "COP")
Fiat.find_or_create_by(ticker: "CRC")
Fiat.find_or_create_by(ticker: "CUC")
Fiat.find_or_create_by(ticker: "CUP")
Fiat.find_or_create_by(ticker: "CVE")
Fiat.find_or_create_by(ticker: "CZK")
Fiat.find_or_create_by(ticker: "DAI")
Fiat.find_or_create_by(ticker: "DJF")
Fiat.find_or_create_by(ticker: "DKK")
Fiat.find_or_create_by(ticker: "DOP")
Fiat.find_or_create_by(ticker: "DZD")
Fiat.find_or_create_by(ticker: "EGP")
Fiat.find_or_create_by(ticker: "ERN")
Fiat.find_or_create_by(ticker: "ETB")
Fiat.find_or_create_by(ticker: "ETH")
Fiat.find_or_create_by(ticker: "EUR")
Fiat.find_or_create_by(ticker: "FJD")
Fiat.find_or_create_by(ticker: "FKP")
Fiat.find_or_create_by(ticker: "FTM")
Fiat.find_or_create_by(ticker: "GBP")
Fiat.find_or_create_by(ticker: "GEL")
Fiat.find_or_create_by(ticker: "GGP")
Fiat.find_or_create_by(ticker: "GHS")
Fiat.find_or_create_by(ticker: "GIP")
Fiat.find_or_create_by(ticker: "GMD")
Fiat.find_or_create_by(ticker: "GNF")
Fiat.find_or_create_by(ticker: "GTQ")
Fiat.find_or_create_by(ticker: "GYD")
Fiat.find_or_create_by(ticker: "HARMONY")
Fiat.find_or_create_by(ticker: "HKD")
Fiat.find_or_create_by(ticker: "HNL")
Fiat.find_or_create_by(ticker: "HRK")
Fiat.find_or_create_by(ticker: "HT")
Fiat.find_or_create_by(ticker: "HTG")
Fiat.find_or_create_by(ticker: "HUF")
Fiat.find_or_create_by(ticker: "IDR")
Fiat.find_or_create_by(ticker: "ILS")
Fiat.find_or_create_by(ticker: "IMP")
Fiat.find_or_create_by(ticker: "INR")
Fiat.find_or_create_by(ticker: "IQD")
Fiat.find_or_create_by(ticker: "IRR")
Fiat.find_or_create_by(ticker: "ISK")
Fiat.find_or_create_by(ticker: "JEP")
Fiat.find_or_create_by(ticker: "JMD")
Fiat.find_or_create_by(ticker: "JOD")
Fiat.find_or_create_by(ticker: "JPY")
Fiat.find_or_create_by(ticker: "KES")
Fiat.find_or_create_by(ticker: "KGS")
Fiat.find_or_create_by(ticker: "KHR")
Fiat.find_or_create_by(ticker: "KMF")
Fiat.find_or_create_by(ticker: "KPW")
Fiat.find_or_create_by(ticker: "KRW")
Fiat.find_or_create_by(ticker: "KWD")
Fiat.find_or_create_by(ticker: "KYD")
Fiat.find_or_create_by(ticker: "KZT")
Fiat.find_or_create_by(ticker: "LAK")
Fiat.find_or_create_by(ticker: "LBP")
Fiat.find_or_create_by(ticker: "LKR")
Fiat.find_or_create_by(ticker: "LRD")
Fiat.find_or_create_by(ticker: "LSL")
Fiat.find_or_create_by(ticker: "LTL")
Fiat.find_or_create_by(ticker: "LVL")
Fiat.find_or_create_by(ticker: "LYD")
Fiat.find_or_create_by(ticker: "MAD")
Fiat.find_or_create_by(ticker: "MATIC")
Fiat.find_or_create_by(ticker: "MDL")
Fiat.find_or_create_by(ticker: "MGA")
Fiat.find_or_create_by(ticker: "MKD")
Fiat.find_or_create_by(ticker: "MMK")
Fiat.find_or_create_by(ticker: "MNT")
Fiat.find_or_create_by(ticker: "MOP")
Fiat.find_or_create_by(ticker: "MRO")
Fiat.find_or_create_by(ticker: "MUR")
Fiat.find_or_create_by(ticker: "MVR")
Fiat.find_or_create_by(ticker: "MWK")
Fiat.find_or_create_by(ticker: "MXN")
Fiat.find_or_create_by(ticker: "MYR")
Fiat.find_or_create_by(ticker: "MZN")
Fiat.find_or_create_by(ticker: "NAD")
Fiat.find_or_create_by(ticker: "NEAR")
Fiat.find_or_create_by(ticker: "NGN")
Fiat.find_or_create_by(ticker: "NIO")
Fiat.find_or_create_by(ticker: "NOK")
Fiat.find_or_create_by(ticker: "NPR")
Fiat.find_or_create_by(ticker: "NZD")
Fiat.find_or_create_by(ticker: "OMR")
Fiat.find_or_create_by(ticker: "PAB")
Fiat.find_or_create_by(ticker: "PEN")
Fiat.find_or_create_by(ticker: "PGK")
Fiat.find_or_create_by(ticker: "PHP")
Fiat.find_or_create_by(ticker: "PKR")
Fiat.find_or_create_by(ticker: "PLN")
Fiat.find_or_create_by(ticker: "PYG")
Fiat.find_or_create_by(ticker: "QAR")
Fiat.find_or_create_by(ticker: "RON")
Fiat.find_or_create_by(ticker: "RSD")
Fiat.find_or_create_by(ticker: "RUB")
Fiat.find_or_create_by(ticker: "RWF")
Fiat.find_or_create_by(ticker: "SAR")
Fiat.find_or_create_by(ticker: "SBD")
Fiat.find_or_create_by(ticker: "SCR")
Fiat.find_or_create_by(ticker: "SDG")
Fiat.find_or_create_by(ticker: "SEK")
Fiat.find_or_create_by(ticker: "SGD")
Fiat.find_or_create_by(ticker: "SHP")
Fiat.find_or_create_by(ticker: "SLL")
Fiat.find_or_create_by(ticker: "SOL")
Fiat.find_or_create_by(ticker: "SOS")
Fiat.find_or_create_by(ticker: "SRD")
Fiat.find_or_create_by(ticker: "STD")
Fiat.find_or_create_by(ticker: "SVC")
Fiat.find_or_create_by(ticker: "SYP")
Fiat.find_or_create_by(ticker: "SZL")
Fiat.find_or_create_by(ticker: "THB")
Fiat.find_or_create_by(ticker: "TJS")
Fiat.find_or_create_by(ticker: "TMT")
Fiat.find_or_create_by(ticker: "TND")
Fiat.find_or_create_by(ticker: "TOP")
Fiat.find_or_create_by(ticker: "TRX")
Fiat.find_or_create_by(ticker: "TRY")
Fiat.find_or_create_by(ticker: "TTD")
Fiat.find_or_create_by(ticker: "TWD")
Fiat.find_or_create_by(ticker: "TZS")
Fiat.find_or_create_by(ticker: "UAH")
Fiat.find_or_create_by(ticker: "UGX")
Fiat.find_or_create_by(ticker: "USD")
Fiat.find_or_create_by(ticker: "USDC")
Fiat.find_or_create_by(ticker: "USDT")
Fiat.find_or_create_by(ticker: "UYU")
Fiat.find_or_create_by(ticker: "UZS")
Fiat.find_or_create_by(ticker: "VEF")
Fiat.find_or_create_by(ticker: "VND")
Fiat.find_or_create_by(ticker: "VUV")
Fiat.find_or_create_by(ticker: "WBTC")
Fiat.find_or_create_by(ticker: "WST")
Fiat.find_or_create_by(ticker: "XAF")
Fiat.find_or_create_by(ticker: "XAG")
Fiat.find_or_create_by(ticker: "XAU")
Fiat.find_or_create_by(ticker: "XCD")
Fiat.find_or_create_by(ticker: "XDR")
Fiat.find_or_create_by(ticker: "XOF")
Fiat.find_or_create_by(ticker: "XPF")
Fiat.find_or_create_by(ticker: "YER")
Fiat.find_or_create_by(ticker: "ZAR")
Fiat.find_or_create_by(ticker: "ZIL")
Fiat.find_or_create_by(ticker: "ZMK")
Fiat.find_or_create_by(ticker: "ZMW")
Fiat.find_or_create_by(ticker: "ZWL")